import type { Opportunity, Requirement } from './model';

const verifiedAt = '2026-09-30T17:25:00Z';
const expandedCatalogVerifiedAt = '2026-09-30T19:38:52Z';

function rule(
  opportunityId: string,
  sourceUrl: string,
  sourceReference: string,
  id: string,
  wording: string,
  rest: Partial<Requirement> = {},
): Requirement {
  return {
    id,
    opportunity_id: opportunityId,
    kind: 'review',
    roles: [],
    formats: [],
    field: null,
    operator: 'review',
    value: null,
    wording,
    source_reference: sourceReference,
    source_url: sourceUrl,
    ...rest,
  };
}

/** Reviewed public webpages — not fabricated. Not automatically inserted into Supabase. */
export const reviewedCatalog: Opportunity[] = [
  {
    id: 'sector-13',
    slug: 'sector-13',
    title: 'Sector 13',
    organizer: 'Box of Rain / Sector House 13',
    category: 'anthology',
    official_url: 'https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/',
    status: 'rolling',
    deadline: null,
    deadline_timezone: null,
    compensation: 'Unpaid: the organizer states that contributors are not paid.',
    rights_disclosure: null,
    last_verified_at: verifiedAt,
    published: true,
    description:
      'Science-fiction comics fanzine seeking writers, sequential artists, and letterers. Recheck the organizer’s page before contacting them.',
    roles: ['writer', 'artist', 'writer-artist', 'letterer', 'team'],
    formats: ['script', 'portfolio'],
    requirements: [
      rule(
        'sector-13',
        'https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/',
        'Sector 13 contributor guidelines',
        's13-script',
        'Have a script or story idea ready to share.',
        { roles: ['writer', 'writer-artist'] },
      ),
      rule(
        'sector-13',
        'https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/',
        'Sector 13 contributor guidelines',
        's13-art',
        'Provide examples of your comics or lettering work.',
        {
          kind: 'preparation',
          roles: ['artist', 'letterer', 'writer-artist'],
          field: 'portfolio',
          operator: 'eq',
          value: true,
        },
      ),
      rule(
        'sector-13',
        'https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/',
        'Sector 13 contributor guidelines',
        's13-length',
        'Stories are generally up to seven pages; longer work may be considered. Confirm exceptions with the organizer.',
        { roles: ['writer', 'writer-artist', 'team'] },
      ),
      rule(
        'sector-13',
        'https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/',
        'Sector 13 contributor guidelines',
        's13-content',
        'Review the science-fiction/fantasy focus, audience guidance, and character restrictions with the organizer.',
      ),
    ],
  },
  {
    id: 'cbk-cba-v76',
    slug: 'cbk-cba-v76',
    title: 'CBA vol 76 — World Without Pictures',
    organizer: 'CBK Comics',
    category: 'anthology',
    official_url: 'https://cbkcomics.com/submissions/',
    status: 'open',
    deadline: '2027-02-15T22:59:59Z',
    deadline_timezone: 'Europe/Stockholm',
    compensation:
      'No guaranteed fee; surplus after costs may be shared. Published contributors receive five complimentary copies (organizer’s stated terms).',
    rights_disclosure: 'Copyright for submitted material remains with the creator (organizer’s stated terms).',
    last_verified_at: verifiedAt,
    published: true,
    description:
      'Experimental comics and texts for CBK’s anthology series. English-language work; high-resolution print files. Recheck the submissions page before sending.',
    roles: ['writer', 'writer-artist', 'artist', 'team'],
    formats: ['completed short comic', 'script'],
    requirements: [
      rule(
        'cbk-cba-v76',
        'https://cbkcomics.com/submissions/',
        'CBK submissions guidelines',
        'cbk-language',
        'Comics and texts should be in English.',
      ),
      rule(
        'cbk-cba-v76',
        'https://cbkcomics.com/submissions/',
        'CBK submissions guidelines',
        'cbk-length',
        'Comics are often about 5–30 pages, but other lengths are welcome. Confirm fit for this volume.',
        { roles: ['writer-artist', 'artist', 'team'] },
      ),
      rule(
        'cbk-cba-v76',
        'https://cbkcomics.com/submissions/',
        'CBK submissions guidelines',
        'cbk-files',
        'Prepare high-resolution print files (.TIF), bleed, and a short bio (about 500–700 characters) with one URL.',
        { kind: 'preparation', field: 'bio', operator: 'eq', value: true },
      ),
      rule(
        'cbk-cba-v76',
        'https://cbkcomics.com/submissions/',
        'CBK submissions guidelines',
        'cbk-ai',
        'Submissions created using AI are not accepted.',
        { kind: 'eligibility' },
      ),
    ],
  },
  {
    id: 'discord-bite',
    slug: 'discord-bite',
    title: 'Bite — bisexual erotic horror anthology',
    organizer: 'Discord Comics',
    category: 'anthology',
    official_url: 'https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/',
    status: 'open',
    deadline: '2026-10-15T22:59:59Z',
    deadline_timezone: 'Europe/London',
    compensation:
      'Stated rates for writers and artists plus profit share after Kickstarter; payment tied to successful funding (see official page).',
    rights_disclosure: 'One year exclusive publishing rights, then creators may reuse work (organizer’s stated terms).',
    last_verified_at: verifiedAt,
    published: true,
    description:
      'Paranormal, mild-horror erotica exploring bisexual themes. Applications from writers, artists, and teams—finished pages not required at submission. 18+ only.',
    roles: ['writer', 'artist', 'writer-artist', 'team'],
    formats: ['pitch', 'portfolio', 'script'],
    requirements: [
      rule(
        'discord-bite',
        'https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/',
        'Bite submission info',
        'bite-age',
        'Applicants must be 18 or older.',
        { kind: 'eligibility' },
      ),
      rule(
        'discord-bite',
        'https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/',
        'Bite submission info',
        'bite-pages',
        'Finished anthology stories are intended to run about 11–21 pages. Confirm length expectations for your role.',
        { roles: ['writer-artist', 'team'] },
      ),
      rule(
        'discord-bite',
        'https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/',
        'Bite submission info',
        'bite-portfolio',
        'Submit examples of prior comic or script work plus a short pitch—not a finished comic.',
        { kind: 'preparation', field: 'portfolio', operator: 'eq', value: true },
      ),
      rule(
        'discord-bite',
        'https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/',
        'Bite submission info',
        'bite-ai',
        'AI-generated content is not accepted.',
        { kind: 'eligibility' },
      ),
    ],
  },
  {
    id: 'icc-smut-peddler-baddies',
    slug: 'icc-smut-peddler-baddies',
    title: 'Smut Peddler Presents: Baddies',
    organizer: 'Iron Circus Comics',
    category: 'anthology',
    official_url: 'https://ironcircus.com/smut-peddler-baddies/',
    status: 'open',
    deadline: '2026-12-01T23:59:59Z',
    deadline_timezone: 'America/Chicago',
    compensation:
      'Paid participation for accepted contributors; rates and terms are stated on the project page and in contributor agreements.',
    rights_disclosure:
      'Universal first publication rights to Iron Circus for one year; general publication rights in perpetuity (organizer’s stated terms).',
    last_verified_at: verifiedAt,
    published: true,
    description:
      'Full-color erotic comics anthology about villains. Proposals with portfolio links—4–20 pages if accepted. 18+ only; recheck the official page before submitting.',
    roles: ['writer', 'artist', 'writer-artist', 'team'],
    formats: ['pitch', 'portfolio'],
    requirements: [
      rule(
        'icc-smut-peddler-baddies',
        'https://ironcircus.com/smut-peddler-baddies/',
        'Smut Peddler Baddies project page',
        'icc-baddies-window',
        'Submissions open 1 October through 1 December 2026 on the organizer’s form (see official page).',
      ),
      rule(
        'icc-smut-peddler-baddies',
        'https://ironcircus.com/smut-peddler-baddies/',
        'Smut Peddler Baddies project page',
        'icc-baddies-pitch',
        'Prepare creator names and emails, story title, a beginning–middle–end summary, estimated page count (4–20), and portfolio links.',
        { kind: 'preparation', field: 'portfolio', operator: 'eq', value: true },
      ),
      rule(
        'icc-smut-peddler-baddies',
        'https://ironcircus.com/smut-peddler-baddies/',
        'Smut Peddler Baddies project page',
        'icc-baddies-mature',
        'Mature erotic content; applicants must meet the organizer’s age requirements.',
        { kind: 'eligibility' },
      ),
    ],
  },
  {
    id: 'thirdbear-2027-singles',
    slug: 'thirdbear-2027-singles',
    title: '2027 standalone single-issue comics',
    organizer: 'ThirdBear Press',
    category: 'short-comic',
    official_url: 'https://thirdbearpress.com/submissions',
    status: 'open',
    deadline: '2026-12-01T23:59:59Z',
    deadline_timezone: 'Europe/London',
    compensation: null,
    rights_disclosure: null,
    last_verified_at: verifiedAt,
    published: true,
    description:
      'ThirdBear Press plans 3–4 standalone 28–32 page comics from UK-based creators for the second half of 2027. Full guidelines appear on the submissions page when applications open—recheck before sending.',
    roles: ['writer-artist', 'artist', 'writer', 'team'],
    formats: ['pitch', 'completed short comic', 'portfolio'],
    requirements: [
      rule(
        'thirdbear-2027-singles',
        'https://thirdbearpress.com/submissions',
        'ThirdBear Press submissions page',
        'tb-window',
        'Submissions run 1 October through 1 December 2026; confirm details on the organizer’s page when live.',
      ),
      rule(
        'thirdbear-2027-singles',
        'https://thirdbearpress.com/submissions',
        'ThirdBear Press submissions page',
        'tb-uk',
        'The call is for UK-based creators. Confirm eligibility with the organizer if your situation is unclear.',
        { kind: 'eligibility', field: 'country', operator: 'review', value: null },
      ),
      rule(
        'thirdbear-2027-singles',
        'https://thirdbearpress.com/submissions',
        'ThirdBear Press submissions page',
        'tb-length',
        'Target format is a standalone single issue of about 28–32 pages. Confirm expectations on the official page.',
        { roles: ['writer-artist', 'team'] },
      ),
    ],
  },
  {
    id: 'birdseye-bebop',
    slug: 'birdseye-bebop',
    title: 'The BeBop anthology',
    organizer: "Bird's Eye Comics",
    category: 'anthology',
    official_url: 'https://birdseyecomics.com/pages/submissions',
    status: 'rolling',
    deadline: null,
    deadline_timezone: null,
    compensation: 'Page rates are negotiated per assignment; payment on completion (organizer’s stated terms).',
    rights_disclosure: 'Artwork produced under assignment is company-owned (organizer’s stated terms).',
    last_verified_at: verifiedAt,
    published: true,
    description:
      'Ongoing anthology series accepting scripts and artist portfolios for current or future issues. Stories often run 1–20 pages. Recheck which issue is open before you pitch.',
    roles: ['writer', 'artist', 'writer-artist', 'colorist', 'letterer', 'team'],
    formats: ['script', 'portfolio', 'pitch'],
    requirements: [
      rule(
        'birdseye-bebop',
        'https://birdseyecomics.com/pages/submissions',
        "Bird's Eye Comics submissions",
        'bebop-script',
        'Writers: send name, contact, experience, portfolio or samples, genre preferences, team details, and story plans to thebebop@birdseyecomics.com.',
        { roles: ['writer'], kind: 'preparation', field: 'script', operator: 'eq', value: true },
      ),
      rule(
        'birdseye-bebop',
        'https://birdseyecomics.com/pages/submissions',
        "Bird's Eye Comics submissions",
        'bebop-art',
        'Artists: include portfolio, experience, social links, preferred roles (inking, color, lettering, etc.), and rates when applying.',
        { roles: ['artist', 'colorist', 'letterer'], kind: 'preparation', field: 'portfolio', operator: 'eq', value: true },
      ),
      rule(
        'birdseye-bebop',
        'https://birdseyecomics.com/pages/submissions',
        "Bird's Eye Comics submissions",
        'bebop-original',
        'Only original content; the organizer states a no-tolerance policy for hate speech.',
        { kind: 'eligibility' },
      ),
    ],
  },
  {
    id: 'kkum-hybrid-horror',
    slug: 'kkum-hybrid-horror',
    title: 'Hybrid Horror Anthology',
    organizer: 'KKUM',
    category: 'anthology',
    official_url: 'https://www.kkum.org/',
    status: 'open',
    deadline: null,
    deadline_timezone: null,
    deadline_note: '15 October 2026; submission time and timezone not stated.',
    compensation: 'Unpaid independent collaboration; contributors are not charged and sales revenue is reinvested in the project (organizer’s stated terms).',
    rights_disclosure: 'Creators retain copyright and ownership; selected contributors grant permission to publish, distribute, and promote the contribution and excerpts. Full terms follow selection.',
    last_verified_at: expandedCatalogVerifiedAt,
    published: true,
    description:
      'International call for original short horror combining prose, illustration, manga, comics, or experimental sequential art. Submit a proposal and samples rather than finished pages.',
    roles: ['writer', 'artist', 'writer-artist', 'team'],
    formats: ['pitch', 'portfolio'],
    requirements: [
      rule('kkum-hybrid-horror', 'https://www.kkum.org/', 'Who Can Apply / Originality', 'kkum-rights', 'Confirm that the proposal is original and that you hold the rights needed to submit and develop it.', {
        kind: 'eligibility', field: 'rights', operator: 'eq', value: true,
      }),
      rule('kkum-hybrid-horror', 'https://www.kkum.org/', 'What Should I Submit — Your Proposal', 'kkum-synopsis', 'Prepare a 150–300 word story synopsis, estimated page count, and preferred format.', {
        kind: 'preparation', field: 'synopsis', operator: 'eq', value: true,
      }),
      rule('kkum-hybrid-horror', 'https://www.kkum.org/', 'What Should I Submit — Work Samples', 'kkum-portfolio', 'Provide three relevant work examples or a portfolio link.', {
        kind: 'preparation', field: 'portfolio', operator: 'eq', value: true,
      }),
      rule('kkum-hybrid-horror', 'https://www.kkum.org/', 'Recommended Length', 'kkum-length', 'The recommended finished length is about 4–12 pages; explain in the application if the idea needs a different length.'),
      rule('kkum-hybrid-horror', 'https://www.kkum.org/', 'Important', 'kkum-not-finished', 'Do not create the complete finished work before selection.'),
    ],
  },
  {
    id: 'afrocomiccon-illustrated-revolution-adult',
    slug: 'afrocomiccon-illustrated-revolution-adult',
    title: 'The Revolution Will Be Illustrated — adult call',
    organizer: 'OTEC / AfroComicCon',
    category: 'anthology',
    official_url: 'https://afrocomiccon.org/illustratedrevolution/',
    status: 'open',
    deadline: null,
    deadline_timezone: null,
    deadline_note: '1 December 2026; submission time and timezone not stated.',
    compensation: '$125–$150 honorarium per accepted page, contingent on successful Spring 2027 Kickstarter funding (organizer’s stated terms).',
    rights_disclosure: 'The organizer states that original owners retain all rights to submitted comics.',
    last_verified_at: expandedCatalogVerifiedAt,
    published: true,
    description:
      'Worldwide adult-artist call for completed illustrations, cartoon strips, and graphic short stories about revolution and transformation. Priority is given to Black and Indigenous artists.',
    roles: ['artist', 'writer-artist', 'team'],
    formats: ['completed short comic'],
    requirements: [
      rule('afrocomiccon-illustrated-revolution-adult', 'https://afrocomiccon.org/illustratedrevolution/', 'Adult Artist Guidelines — What We Are Looking For', 'afro-rights', 'You must own the submitted comic or artwork.', {
        kind: 'eligibility', field: 'rights', operator: 'eq', value: true,
      }),
      rule('afrocomiccon-illustrated-revolution-adult', 'https://afrocomiccon.org/illustratedrevolution/', 'Adult Artist Guidelines — What We Need', 'afro-pages', 'Adult comic submissions may be no longer than 15 pages.', {
        kind: 'eligibility', field: 'storyPages', operator: 'lte', value: 15,
      }),
      rule('afrocomiccon-illustrated-revolution-adult', 'https://afrocomiccon.org/illustratedrevolution/', 'Adult Artist Submission Form', 'afro-bio', 'Prepare a creator biography of no more than 100 words.', {
        kind: 'preparation', field: 'bio', operator: 'eq', value: true,
      }),
      rule('afrocomiccon-illustrated-revolution-adult', 'https://afrocomiccon.org/illustratedrevolution/', 'Adult Artist Submission Form', 'afro-pdf', 'Prepare the completed high-resolution artwork as a PDF or JPG at 300 DPI.', {
        kind: 'preparation', field: 'pdf', operator: 'eq', value: true,
      }),
      rule('afrocomiccon-illustrated-revolution-adult', 'https://afrocomiccon.org/illustratedrevolution/', 'Adult Artist Guidelines / Submission Form', 'afro-size', 'Confirm the required page dimensions with the organizer: the guidelines and upload form publish different sizes.'),
      rule('afrocomiccon-illustrated-revolution-adult', 'https://afrocomiccon.org/illustratedrevolution/', 'Adult Artist Guidelines — What We Are Looking For', 'afro-content', 'The work must uplift marginalized voices, avoid hate speech, and contain no AI-generated content.', { kind: 'eligibility' }),
    ],
  },
  {
    id: 'lumicpress-magazine',
    slug: 'lumicpress-magazine',
    title: 'LumicPress Magazine one-shots',
    organizer: 'LumicPress',
    category: 'short-comic',
    official_url: 'https://lumicpress.com/lumicpress-magazine-submissions/',
    status: 'rolling',
    deadline: null,
    deadline_timezone: null,
    compensation: '$30 USD per published comic page, for 1–5 pages; payment is on publication rather than acceptance (organizer’s stated terms).',
    rights_disclosure: 'Creators retain copyright and ownership and grant a non-exclusive, royalty-free license for one publication; reuse requires permission and additional payment.',
    last_verified_at: expandedCatalogVerifiedAt,
    published: true,
    description:
      'Rolling call for standalone black-and-white, manga-influenced comics for readers ages 6–14. Previously published work is allowed if it is not under an exclusive publishing agreement.',
    roles: ['artist', 'writer-artist', 'team'],
    formats: ['completed short comic'],
    requirements: [
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submission Guidelines', 'lumic-rights', 'Submit only original work that you control; fan art and AI-assisted work are not accepted.', {
        kind: 'eligibility', field: 'rights', operator: 'eq', value: true,
      }),
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submissions', 'lumic-min-pages', 'Comic submissions must contain at least one page.', {
        kind: 'eligibility', field: 'storyPages', operator: 'gte', value: 1,
      }),
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submissions', 'lumic-max-pages', 'Comic submissions may contain no more than five pages.', {
        kind: 'eligibility', field: 'storyPages', operator: 'lte', value: 5,
      }),
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submission Guidelines', 'lumic-age', 'Submitting creators must be 18 or older.'),
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submission Guidelines', 'lumic-audience', 'Content must be suitable for children ages 6–14 and formatted for left-to-right reading.'),
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submission Guidelines', 'lumic-files', 'Prepare black-and-white pages at 8.5 × 11 inches and 300 DPI.'),
    ],
  },
  {
    id: 'viz-one-shots',
    slug: 'viz-one-shots',
    title: 'VIZ manga one-shots',
    organizer: 'VIZ Media',
    category: 'short-comic',
    official_url: 'https://www.viz.com/blog/posts/submission-guidelines',
    status: 'rolling',
    deadline: null,
    deadline_timezone: null,
    compensation: null,
    rights_disclosure: null,
    last_verified_at: expandedCatalogVerifiedAt,
    published: true,
    description:
      'Rolling portal for manga one-shots. Completed pages are preferred, but VIZ states that work in progress and thumbnails with an inked character design may be submitted.',
    roles: ['writer-artist', 'team'],
    formats: ['completed short comic', 'pitch'],
    requirements: [
      rule('viz-one-shots', 'https://www.viz.com/blog/posts/submission-guidelines', 'For One-Shots', 'viz-min-pages', 'A manga one-shot must be at least 20 pages.', {
        kind: 'eligibility', field: 'storyPages', operator: 'gte', value: 20,
      }),
      rule('viz-one-shots', 'https://www.viz.com/blog/posts/submission-guidelines', 'For One-Shots', 'viz-max-pages', 'A manga one-shot may be no longer than 50 pages.', {
        kind: 'eligibility', field: 'storyPages', operator: 'lte', value: 50,
      }),
      rule('viz-one-shots', 'https://www.viz.com/blog/posts/submission-guidelines', 'For both', 'viz-synopsis', 'Prepare a story synopsis covering the direction and atmosphere of the manga.', {
        kind: 'preparation', field: 'synopsis', operator: 'eq', value: true,
      }),
      rule('viz-one-shots', 'https://www.viz.com/blog/posts/submission-guidelines', 'For both', 'viz-bio', 'Include creator biographies and creative goals.', {
        kind: 'preparation', field: 'bio', operator: 'eq', value: true,
      }),
      rule('viz-one-shots', 'https://www.viz.com/blog/posts/submission-guidelines', 'For One-Shots / For both', 'viz-materials', 'Include character descriptions, target audience, comparable titles, and character designs when an artist is attached.'),
    ],
  },
];

const fixtureSource = '/development-guidelines';
export const developmentCall: Opportunity = {
  id: 'dev-anthology',
  slug: 'development-anthology',
  title: 'Practice anthology',
  organizer: 'ComicReady development fixture',
  category: 'anthology',
  official_url: fixtureSource,
  status: 'open',
  deadline: null,
  deadline_timezone: null,
  compensation: null,
  rights_disclosure: null,
  last_verified_at: null,
  published: true,
  fixture: true,
  description: 'A fictional call for testing the checker. Not an opportunity and not accepting applications.',
  roles: ['writer', 'artist', 'writer-artist', 'team'],
  formats: ['pitch', 'completed short comic'],
  requirements: [
    rule('dev-anthology', fixtureSource, 'Development rule A', 'dev-rights', 'You must control the rights needed to submit.', {
      kind: 'eligibility',
      field: 'rights',
      operator: 'eq',
      value: true,
    }),
    rule('dev-anthology', fixtureSource, 'Development rule B', 'dev-team', 'Writers must have an artist collaborator.', {
      kind: 'eligibility',
      roles: ['writer'],
      field: 'collaborator',
      operator: 'eq',
      value: true,
    }),
    rule(
      'dev-anthology',
      fixtureSource,
      'Development rule C',
      'dev-samples',
      'Prepare at least three completed sequential sample pages.',
      { kind: 'preparation', field: 'samplePages', operator: 'gte', value: 3 },
    ),
    rule(
      'dev-anthology',
      fixtureSource,
      'Development rule D',
      'dev-length',
      'The proposed story must be no more than eight pages.',
      { kind: 'eligibility', field: 'storyPages', operator: 'lte', value: 8 },
    ),
    rule('dev-anthology', fixtureSource, 'Development rule E', 'dev-pdf', 'Prepare a submission PDF.', {
      kind: 'preparation',
      field: 'pdf',
      operator: 'eq',
      value: true,
    }),
  ],
};
