import type { Opportunity, Requirement } from './model';

const verifiedAt = '2026-09-30T17:25:00Z';
const expandedCatalogVerifiedAt = '2026-09-30T19:38:52Z';
const secondCatalogExpansionVerifiedAt = '2026-10-01T16:35:18Z';
const thirdCatalogExpansionVerifiedAt = '2026-10-02T13:50:36Z';
const fourthCatalogExpansionVerifiedAt = '2026-10-03T13:42:30Z';

function rule(
  opportunityId: string,
  sourceUrl: string,
  sourceReference: string,
  id: string,
  wording: string,
  rest: Partial<Requirement> = {},
): Requirement {
  return {
    id,
    opportunity_id: opportunityId,
    kind: 'review',
    roles: [],
    formats: [],
    field: null,
    operator: 'review',
    value: null,
    wording,
    source_reference: sourceReference,
    source_url: sourceUrl,
    ...rest,
  };
}

/** Reviewed public webpages — not fabricated. Not automatically inserted into Supabase. */
export const reviewedCatalog: Opportunity[] = [
  {
    id: 'sector-13',
    slug: 'sector-13',
    title: 'Sector 13',
    organizer: 'Box of Rain / Sector House 13',
    category: 'anthology',
    official_url: 'https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/',
    status: 'rolling',
    deadline: null,
    deadline_timezone: null,
    deadline_date: null,
    compensation: 'Unpaid: the organizer states that contributors are not paid.',
    compensation_type: 'unpaid',
    region_scope: 'not-stated',
    rights_disclosure: null,
    last_verified_at: verifiedAt,
    published: true,
    description:
      'Science-fiction comics fanzine seeking writers, sequential artists, and letterers. Recheck the organizer’s page before contacting them.',
    roles: ['writer', 'artist', 'writer-artist', 'letterer', 'team'],
    formats: ['script', 'portfolio'],
    requirements: [
      rule(
        'sector-13',
        'https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/',
        'Sector 13 contributor guidelines',
        's13-script',
        'Have a script or story idea ready to share.',
        { roles: ['writer', 'writer-artist'] },
      ),
      rule(
        'sector-13',
        'https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/',
        'Sector 13 contributor guidelines',
        's13-art',
        'Provide examples of your comics or lettering work.',
        {
          kind: 'preparation',
          roles: ['artist', 'letterer', 'writer-artist'],
          field: 'portfolio',
          operator: 'eq',
          value: true,
        },
      ),
      rule(
        'sector-13',
        'https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/',
        'Sector 13 contributor guidelines',
        's13-length',
        'Stories are generally up to seven pages; longer work may be considered. Confirm exceptions with the organizer.',
        { roles: ['writer', 'writer-artist', 'team'] },
      ),
      rule(
        'sector-13',
        'https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/',
        'Sector 13 contributor guidelines',
        's13-content',
        'Review the science-fiction/fantasy focus, audience guidance, and character restrictions with the organizer.',
      ),
    ],
  },
  {
    id: 'cbk-cba-v76',
    slug: 'cbk-cba-v76',
    title: 'CBA vol 76 — World Without Pictures',
    organizer: 'CBK Comics',
    category: 'anthology',
    official_url: 'https://cbkcomics.com/submissions/',
    status: 'open',
    deadline: '2027-02-15T22:59:59Z',
    deadline_timezone: 'Europe/Stockholm',
    deadline_date: '2027-02-15',
    compensation:
      'No guaranteed fee; surplus after costs may be shared. Published contributors receive five complimentary copies (organizer’s stated terms).',
    compensation_type: 'conditional',
    region_scope: 'not-stated',
    rights_disclosure: 'Copyright for submitted material remains with the creator (organizer’s stated terms).',
    last_verified_at: verifiedAt,
    published: true,
    description:
      'Experimental comics and texts for CBK’s anthology series. English-language work; high-resolution print files. Recheck the submissions page before sending.',
    roles: ['writer', 'writer-artist', 'artist', 'team'],
    formats: ['completed short comic', 'script'],
    requirements: [
      rule(
        'cbk-cba-v76',
        'https://cbkcomics.com/submissions/',
        'CBK submissions guidelines',
        'cbk-language',
        'Comics and texts should be in English.',
        { kind: 'eligibility', field: 'english', operator: 'eq', value: true },
      ),
      rule(
        'cbk-cba-v76',
        'https://cbkcomics.com/submissions/',
        'CBK submissions guidelines',
        'cbk-length',
        'Comics are often about 5–30 pages, but other lengths are welcome. Confirm fit for this volume.',
        { roles: ['writer-artist', 'artist', 'team'] },
      ),
      rule(
        'cbk-cba-v76',
        'https://cbkcomics.com/submissions/',
        'CBK submissions guidelines',
        'cbk-files',
        'Prepare a short bio (about 500–700 characters) with one URL.',
        { kind: 'preparation', field: 'bio', operator: 'eq', value: true },
      ),
      rule(
        'cbk-cba-v76',
        'https://cbkcomics.com/submissions/',
        'CBK submissions guidelines',
        'cbk-format',
        'Prepare the high-resolution print artwork as .TIF files with bleed.',
        { kind: 'preparation', field: 'fileFormat', operator: 'in', value: ['tif'] },
      ),
      rule(
        'cbk-cba-v76',
        'https://cbkcomics.com/submissions/',
        'CBK submissions guidelines',
        'cbk-ai',
        'Submissions created using AI are not accepted.',
        { kind: 'eligibility', field: 'aiUsed', operator: 'eq', value: false },
      ),
    ],
  },
  {
    id: 'discord-bite',
    slug: 'discord-bite',
    title: 'Bite — bisexual erotic horror anthology',
    organizer: 'Discord Comics',
    category: 'anthology',
    official_url: 'https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/',
    status: 'open',
    deadline: '2026-10-15T22:59:59Z',
    deadline_timezone: 'Europe/London',
    deadline_date: '2026-10-15',
    compensation:
      'Stated rates for writers and artists plus profit share after Kickstarter; payment tied to successful funding (see official page).',
    compensation_type: 'conditional',
    region_scope: 'not-stated',
    rights_disclosure: 'One year exclusive publishing rights, then creators may reuse work (organizer’s stated terms).',
    last_verified_at: verifiedAt,
    published: true,
    description:
      'Paranormal, mild-horror erotica exploring bisexual themes. Applications from writers, artists, and teams—finished pages not required at submission. 18+ only.',
    roles: ['writer', 'artist', 'writer-artist', 'team'],
    formats: ['pitch', 'portfolio', 'script'],
    requirements: [
      rule(
        'discord-bite',
        'https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/',
        'Bite submission info',
        'bite-age',
        'Applicants must be 18 or older.',
        { kind: 'eligibility', field: 'age', operator: 'gte', value: 18 },
      ),
      rule(
        'discord-bite',
        'https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/',
        'Bite submission info',
        'bite-pages',
        'Finished anthology stories are intended to run about 11–21 pages. Confirm length expectations for your role.',
        { roles: ['writer-artist', 'team'] },
      ),
      rule(
        'discord-bite',
        'https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/',
        'Bite submission info',
        'bite-portfolio',
        'Submit examples of prior comic or script work plus a short pitch—not a finished comic.',
        { kind: 'preparation', field: 'portfolio', operator: 'eq', value: true },
      ),
      rule(
        'discord-bite',
        'https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/',
        'Bite submission info',
        'bite-ai',
        'AI-generated content is not accepted.',
        { kind: 'eligibility', field: 'aiUsed', operator: 'eq', value: false },
      ),
    ],
  },
  {
    id: 'icc-smut-peddler-baddies',
    slug: 'icc-smut-peddler-baddies',
    title: 'Smut Peddler Presents: Baddies',
    organizer: 'Iron Circus Comics',
    category: 'anthology',
    official_url: 'https://ironcircus.com/smut-peddler-baddies/',
    status: 'open',
    deadline: '2026-12-01T23:59:59Z',
    deadline_timezone: 'America/Chicago',
    deadline_date: '2026-12-01',
    compensation:
      'Paid participation for accepted contributors; rates and terms are stated on the project page and in contributor agreements.',
    compensation_type: 'paid',
    region_scope: 'not-stated',
    rights_disclosure:
      'Universal first publication rights to Iron Circus for one year; general publication rights in perpetuity (organizer’s stated terms).',
    last_verified_at: verifiedAt,
    published: true,
    description:
      'Full-color erotic comics anthology about villains. Proposals with portfolio links—4–20 pages if accepted. 18+ only; recheck the official page before submitting.',
    roles: ['writer', 'artist', 'writer-artist', 'team'],
    formats: ['pitch', 'portfolio'],
    requirements: [
      rule(
        'icc-smut-peddler-baddies',
        'https://ironcircus.com/smut-peddler-baddies/',
        'Smut Peddler Baddies project page',
        'icc-baddies-window',
        'Submissions open 1 October through 1 December 2026 on the organizer’s form (see official page).',
      ),
      rule(
        'icc-smut-peddler-baddies',
        'https://ironcircus.com/smut-peddler-baddies/',
        'Smut Peddler Baddies project page',
        'icc-baddies-pitch',
        'Prepare creator names and emails, story title, a beginning–middle–end summary, estimated page count (4–20), and portfolio links.',
        { kind: 'preparation', field: 'portfolio', operator: 'eq', value: true },
      ),
      rule(
        'icc-smut-peddler-baddies',
        'https://ironcircus.com/smut-peddler-baddies/',
        'Smut Peddler Baddies project page',
        'icc-baddies-mature',
        'Applicants must be 18 or older because the anthology contains mature erotic content.',
        { kind: 'eligibility', field: 'age', operator: 'gte', value: 18 },
      ),
    ],
  },
  {
    id: 'thirdbear-2027-singles',
    slug: 'thirdbear-2027-singles',
    title: '2027 standalone single-issue comics',
    organizer: 'ThirdBear Press',
    category: 'short-comic',
    official_url: 'https://thirdbearpress.com/submissions',
    status: 'open',
    deadline: '2026-12-01T23:59:59Z',
    deadline_timezone: 'Europe/London',
    deadline_date: '2026-12-01',
    compensation: null,
    compensation_type: 'undisclosed',
    region_scope: 'restricted',
    rights_disclosure: null,
    last_verified_at: verifiedAt,
    published: true,
    description:
      'ThirdBear Press plans 3–4 standalone 28–32 page comics from UK-based creators for the second half of 2027. Full guidelines appear on the submissions page when applications open—recheck before sending.',
    roles: ['writer-artist', 'artist', 'writer', 'team'],
    formats: ['pitch', 'completed short comic', 'portfolio'],
    requirements: [
      rule(
        'thirdbear-2027-singles',
        'https://thirdbearpress.com/submissions',
        'ThirdBear Press submissions page',
        'tb-window',
        'Submissions run 1 October through 1 December 2026; confirm details on the organizer’s page when live.',
      ),
      rule(
        'thirdbear-2027-singles',
        'https://thirdbearpress.com/submissions',
        'ThirdBear Press submissions page',
        'tb-uk',
        'The call is for UK-based creators. Confirm eligibility with the organizer if your situation is unclear.',
        { kind: 'eligibility', field: 'country', operator: 'in', value: ['GB'] },
      ),
      rule(
        'thirdbear-2027-singles',
        'https://thirdbearpress.com/submissions',
        'ThirdBear Press submissions page',
        'tb-length',
        'Target format is a standalone single issue of about 28–32 pages. Confirm expectations on the official page.',
        { roles: ['writer-artist', 'team'] },
      ),
    ],
  },
  {
    id: 'birdseye-bebop',
    slug: 'birdseye-bebop',
    title: 'The BeBop anthology',
    organizer: "Bird's Eye Comics",
    category: 'anthology',
    official_url: 'https://birdseyecomics.com/pages/submissions',
    status: 'rolling',
    deadline: null,
    deadline_timezone: null,
    deadline_date: null,
    compensation: 'Page rates are negotiated per assignment; payment on completion (organizer’s stated terms).',
    compensation_type: 'paid',
    region_scope: 'not-stated',
    rights_disclosure: 'Artwork produced under assignment is company-owned (organizer’s stated terms).',
    last_verified_at: verifiedAt,
    published: true,
    description:
      'Ongoing anthology series accepting scripts and artist portfolios for current or future issues. Stories often run 1–20 pages. Recheck which issue is open before you pitch.',
    roles: ['writer', 'artist', 'writer-artist', 'colorist', 'letterer', 'team'],
    formats: ['script', 'portfolio', 'pitch'],
    requirements: [
      rule(
        'birdseye-bebop',
        'https://birdseyecomics.com/pages/submissions',
        "Bird's Eye Comics submissions",
        'bebop-script',
        'Writers: send name, contact, experience, portfolio or samples, genre preferences, team details, and story plans to thebebop@birdseyecomics.com.',
        { roles: ['writer'], kind: 'preparation', field: 'script', operator: 'eq', value: true },
      ),
      rule(
        'birdseye-bebop',
        'https://birdseyecomics.com/pages/submissions',
        "Bird's Eye Comics submissions",
        'bebop-art',
        'Artists: include portfolio, experience, social links, preferred roles (inking, color, lettering, etc.), and rates when applying.',
        { roles: ['artist', 'colorist', 'letterer'], kind: 'preparation', field: 'portfolio', operator: 'eq', value: true },
      ),
      rule(
        'birdseye-bebop',
        'https://birdseyecomics.com/pages/submissions',
        "Bird's Eye Comics submissions",
        'bebop-original',
        'Only original content; the organizer states a no-tolerance policy for hate speech.',
        { kind: 'eligibility', field: 'rights', operator: 'eq', value: true },
      ),
    ],
  },
  {
    id: 'kkum-hybrid-horror',
    slug: 'kkum-hybrid-horror',
    title: 'Hybrid Horror Anthology',
    organizer: 'KKUM',
    category: 'anthology',
    official_url: 'https://www.kkum.org/',
    status: 'open',
    deadline: null,
    deadline_timezone: null,
    deadline_note: '15 October 2026; submission time and timezone not stated.',
    deadline_date: '2026-10-15',
    compensation: 'Unpaid independent collaboration; contributors are not charged and sales revenue is reinvested in the project (organizer’s stated terms).',
    compensation_type: 'unpaid',
    region_scope: 'worldwide',
    rights_disclosure: 'Creators retain copyright and ownership; selected contributors grant permission to publish, distribute, and promote the contribution and excerpts. Full terms follow selection.',
    last_verified_at: expandedCatalogVerifiedAt,
    published: true,
    description:
      'International call for original short horror combining prose, illustration, manga, comics, or experimental sequential art. Submit a proposal and samples rather than finished pages.',
    roles: ['writer', 'artist', 'writer-artist', 'team'],
    formats: ['pitch', 'portfolio'],
    requirements: [
      rule('kkum-hybrid-horror', 'https://www.kkum.org/', 'Who Can Apply / Originality', 'kkum-rights', 'Confirm that the proposal is original and that you hold the rights needed to submit and develop it.', {
        kind: 'eligibility', field: 'rights', operator: 'eq', value: true,
      }),
      rule('kkum-hybrid-horror', 'https://www.kkum.org/', 'What Should I Submit — Your Proposal', 'kkum-synopsis', 'Prepare a 150–300 word story synopsis, estimated page count, and preferred format.', {
        kind: 'preparation', field: 'synopsis', operator: 'eq', value: true,
      }),
      rule('kkum-hybrid-horror', 'https://www.kkum.org/', 'What Should I Submit — Work Samples', 'kkum-portfolio', 'Provide three relevant work examples or a portfolio link.', {
        kind: 'preparation', field: 'portfolio', operator: 'eq', value: true,
      }),
      rule('kkum-hybrid-horror', 'https://www.kkum.org/', 'What Should I Propose?', 'kkum-genre', 'The proposal should be an original short horror work in one or more of the listed visual or written formats.', {
        kind: 'eligibility', field: 'genreFit', operator: 'eq', value: true,
      }),
      rule('kkum-hybrid-horror', 'https://www.kkum.org/', 'About Your Work', 'kkum-team-roles', 'Teams should identify each collaborator and their role in the proposal.', {
        kind: 'preparation', roles: ['team'], field: 'teamRoles', operator: 'eq', value: true,
      }),
      rule('kkum-hybrid-horror', 'https://www.kkum.org/', 'Recommended Length', 'kkum-length', 'The recommended finished length is about 4–12 pages; explain in the application if the idea needs a different length.'),
      rule('kkum-hybrid-horror', 'https://www.kkum.org/', 'Important', 'kkum-not-finished', 'Do not create the complete finished work before selection.'),
    ],
  },
  {
    id: 'afrocomiccon-illustrated-revolution-adult',
    slug: 'afrocomiccon-illustrated-revolution-adult',
    title: 'The Revolution Will Be Illustrated — adult call',
    organizer: 'OTEC / AfroComicCon',
    category: 'anthology',
    official_url: 'https://afrocomiccon.org/illustratedrevolution/',
    status: 'open',
    deadline: null,
    deadline_timezone: null,
    deadline_note: '1 December 2026; submission time and timezone not stated.',
    deadline_date: '2026-12-01',
    compensation: '$125–$150 honorarium per accepted page, contingent on successful Spring 2027 Kickstarter funding (organizer’s stated terms).',
    compensation_type: 'conditional',
    region_scope: 'worldwide',
    rights_disclosure: 'The organizer states that original owners retain all rights to submitted comics.',
    last_verified_at: expandedCatalogVerifiedAt,
    published: true,
    description:
      'Worldwide adult-artist call for completed illustrations, cartoon strips, and graphic short stories about revolution and transformation. Priority is given to Black and Indigenous artists.',
    roles: ['artist', 'writer-artist', 'team'],
    formats: ['completed short comic'],
    requirements: [
      rule('afrocomiccon-illustrated-revolution-adult', 'https://afrocomiccon.org/illustratedrevolution/', 'Adult Artist Guidelines — What We Are Looking For', 'afro-rights', 'You must own the submitted comic or artwork.', {
        kind: 'eligibility', field: 'rights', operator: 'eq', value: true,
      }),
      rule('afrocomiccon-illustrated-revolution-adult', 'https://afrocomiccon.org/illustratedrevolution/', 'Adult Artist Guidelines — What We Need', 'afro-pages', 'Adult comic submissions may be no longer than 15 pages.', {
        kind: 'eligibility', field: 'storyPages', operator: 'lte', value: 15,
      }),
      rule('afrocomiccon-illustrated-revolution-adult', 'https://afrocomiccon.org/illustratedrevolution/', 'Adult Artist Submission Form', 'afro-bio', 'Prepare a creator biography of no more than 100 words.', {
        kind: 'preparation', field: 'bio', operator: 'eq', value: true,
      }),
      rule('afrocomiccon-illustrated-revolution-adult', 'https://afrocomiccon.org/illustratedrevolution/', 'Adult Artist Submission Form', 'afro-pdf', 'Prepare the completed high-resolution artwork as a PDF or JPG at 300 DPI.', {
        kind: 'preparation', field: 'fileFormat', operator: 'in', value: ['pdf', 'jpg'],
      }),
      rule('afrocomiccon-illustrated-revolution-adult', 'https://afrocomiccon.org/illustratedrevolution/', 'Adult Artist Submission Form', 'afro-dpi', 'Export the completed artwork at 300 DPI or higher.', {
        kind: 'preparation', field: 'dpi', operator: 'gte', value: 300,
      }),
      rule('afrocomiccon-illustrated-revolution-adult', 'https://afrocomiccon.org/illustratedrevolution/', 'Adult Artist Guidelines / Submission Form', 'afro-size', 'Confirm the required page dimensions with the organizer: the guidelines and upload form publish different sizes.'),
      rule('afrocomiccon-illustrated-revolution-adult', 'https://afrocomiccon.org/illustratedrevolution/', 'Adult Artist Guidelines — What We Are Looking For', 'afro-content', 'The work must uplift marginalized voices and avoid hate speech.', {
        kind: 'eligibility', field: 'audienceFit', operator: 'eq', value: true,
      }),
      rule('afrocomiccon-illustrated-revolution-adult', 'https://afrocomiccon.org/illustratedrevolution/', 'Adult Artist Guidelines — What We Are Looking For', 'afro-ai', 'AI-generated content is not accepted.', {
        kind: 'eligibility', field: 'aiUsed', operator: 'eq', value: false,
      }),
    ],
  },
  {
    id: 'lumicpress-magazine',
    slug: 'lumicpress-magazine',
    title: 'LumicPress Magazine one-shots',
    organizer: 'LumicPress',
    category: 'short-comic',
    official_url: 'https://lumicpress.com/lumicpress-magazine-submissions/',
    status: 'rolling',
    deadline: null,
    deadline_timezone: null,
    deadline_date: null,
    compensation: '$30 USD per published comic page, for 1–5 pages; payment is on publication rather than acceptance (organizer’s stated terms).',
    compensation_type: 'paid',
    region_scope: 'not-stated',
    rights_disclosure: 'Creators retain copyright and ownership and grant a non-exclusive, royalty-free license for one publication; reuse requires permission and additional payment.',
    last_verified_at: expandedCatalogVerifiedAt,
    published: true,
    description:
      'Rolling call for standalone black-and-white, manga-influenced comics for readers ages 6–14. Previously published work is allowed if it is not under an exclusive publishing agreement.',
    roles: ['artist', 'writer-artist', 'team'],
    formats: ['completed short comic'],
    requirements: [
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submission Guidelines', 'lumic-rights', 'Submit only original work that you control; fan art is not accepted.', {
        kind: 'eligibility', field: 'rights', operator: 'eq', value: true,
      }),
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submissions', 'lumic-min-pages', 'Comic submissions must contain at least one page.', {
        kind: 'eligibility', field: 'storyPages', operator: 'gte', value: 1,
      }),
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submissions', 'lumic-max-pages', 'Comic submissions may contain no more than five pages.', {
        kind: 'eligibility', field: 'storyPages', operator: 'lte', value: 5,
      }),
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submission Guidelines', 'lumic-age', 'Submitting creators must be 18 or older.', {
        kind: 'eligibility', field: 'age', operator: 'gte', value: 18,
      }),
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submission Guidelines', 'lumic-ai', 'AI-assisted work is not accepted.', {
        kind: 'eligibility', field: 'aiUsed', operator: 'eq', value: false,
      }),
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submission Guidelines', 'lumic-audience', 'Content must be suitable for children ages 6–14.', {
        kind: 'eligibility', field: 'audienceFit', operator: 'eq', value: true,
      }),
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submission Guidelines', 'lumic-reading', 'Confirm that the comic is formatted for left-to-right reading.'),
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submission Guidelines', 'lumic-dpi', 'Prepare the final pages at 300 DPI or higher.', {
        kind: 'preparation', field: 'dpi', operator: 'gte', value: 300,
      }),
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submission Guidelines', 'lumic-color', 'Prepare the final pages in black and white.', {
        kind: 'preparation', field: 'colorMode', operator: 'in', value: ['black-and-white'],
      }),
      rule('lumicpress-magazine', 'https://lumicpress.com/lumicpress-magazine-submissions/', 'Submission Guidelines', 'lumic-dimensions', 'Prepare the final pages at 8.5 × 11 inches.', {
        kind: 'preparation', field: 'dimensionsReady', operator: 'eq', value: true,
      }),
    ],
  },
  {
    id: 'viz-one-shots',
    slug: 'viz-one-shots',
    title: 'VIZ manga one-shots',
    organizer: 'VIZ Media',
    category: 'short-comic',
    official_url: 'https://www.viz.com/blog/posts/submission-guidelines',
    status: 'rolling',
    deadline: null,
    deadline_timezone: null,
    deadline_date: null,
    compensation: null,
    compensation_type: 'undisclosed',
    region_scope: 'not-stated',
    rights_disclosure: null,
    last_verified_at: expandedCatalogVerifiedAt,
    published: true,
    description:
      'Rolling portal for manga one-shots. Completed pages are preferred, but VIZ states that work in progress and thumbnails with an inked character design may be submitted.',
    roles: ['writer-artist', 'team'],
    formats: ['completed short comic', 'pitch'],
    requirements: [
      rule('viz-one-shots', 'https://www.viz.com/blog/posts/submission-guidelines', 'For One-Shots', 'viz-min-pages', 'A manga one-shot must be at least 20 pages.', {
        kind: 'eligibility', field: 'storyPages', operator: 'gte', value: 20,
      }),
      rule('viz-one-shots', 'https://www.viz.com/blog/posts/submission-guidelines', 'For One-Shots', 'viz-max-pages', 'A manga one-shot may be no longer than 50 pages.', {
        kind: 'eligibility', field: 'storyPages', operator: 'lte', value: 50,
      }),
      rule('viz-one-shots', 'https://www.viz.com/blog/posts/submission-guidelines', 'For both', 'viz-synopsis', 'Prepare a story synopsis covering the direction and atmosphere of the manga.', {
        kind: 'preparation', field: 'synopsis', operator: 'eq', value: true,
      }),
      rule('viz-one-shots', 'https://www.viz.com/blog/posts/submission-guidelines', 'For both', 'viz-bio', 'Include creator biographies and creative goals.', {
        kind: 'preparation', field: 'bio', operator: 'eq', value: true,
      }),
      rule('viz-one-shots', 'https://www.viz.com/blog/posts/submission-guidelines', 'For One-Shots / For both', 'viz-materials', 'Include character descriptions, target audience, comparable titles, and character designs when an artist is attached.'),
    ],
  },
  {
    id: 'dirty-water-hot-off-the-press',
    slug: 'dirty-water-hot-off-the-press',
    title: 'Hot off the Press',
    organizer: 'Dirty Water Comics',
    category: 'short-comic',
    official_url: 'https://www.dirtywatercomics.com/submissions/hotoffthepress',
    status: 'rolling',
    deadline: null,
    deadline_timezone: null,
    deadline_date: null,
    compensation: 'Selected creators receive an honorarium; the organizer does not publish the amount or payment timing.',
    compensation_type: 'paid',
    region_scope: 'not-stated',
    rights_disclosure: null,
    last_verified_at: secondCatalogExpansionVerifiedAt,
    published: true,
    description: 'Rolling digital showcase for previously unpublished standalone comics or excerpts from completed work, especially nonfiction, autobiographical, political, historical, and formally eclectic comics.',
    roles: ['artist', 'writer-artist', 'team'],
    formats: ['completed short comic'],
    requirements: [
      rule('dirty-water-hot-off-the-press', 'https://www.dirtywatercomics.com/submissions/hotoffthepress', 'What Should I Submit?', 'dirty-water-unpublished', 'Submit a comic or excerpt that has not been published previously.', {
        kind: 'eligibility', field: 'previouslyPublished', operator: 'eq', value: false,
      }),
      rule('dirty-water-hot-off-the-press', 'https://www.dirtywatercomics.com/submissions/hotoffthepress', 'What Should I Submit?', 'dirty-water-min-pages', 'The submission must contain at least one comic page.', {
        kind: 'eligibility', field: 'storyPages', operator: 'gte', value: 1,
      }),
      rule('dirty-water-hot-off-the-press', 'https://www.dirtywatercomics.com/submissions/hotoffthepress', 'What Should I Submit?', 'dirty-water-max-pages', 'The submission may contain no more than 15 pages.', {
        kind: 'eligibility', field: 'storyPages', operator: 'lte', value: 15,
      }),
      rule('dirty-water-hot-off-the-press', 'https://www.dirtywatercomics.com/submissions/hotoffthepress', 'We are interested in / What Should I Submit?', 'dirty-water-focus', 'Review the literary and nonfiction focus and the restrictions on conventional superhero, horror, science-fiction, and fantasy work.'),
      rule('dirty-water-hot-off-the-press', 'https://www.dirtywatercomics.com/submissions/hotoffthepress', 'Submission instructions', 'dirty-water-email', 'Email the completed submission with “Hot off the Press” in the subject line.'),
    ],
  },
  {
    id: 'grub-street-volume-76-comics',
    slug: 'grub-street-volume-76-comics',
    title: 'Grub Street Volume 76 — comics',
    organizer: 'Grub Street Literary Magazine',
    category: 'short-comic',
    official_url: 'https://grubstreet.submittable.com/submit',
    status: 'open',
    deadline: null,
    deadline_timezone: null,
    deadline_date: '2026-12-15',
    deadline_note: '15 December 2026; submission time and timezone not stated.',
    compensation: null,
    compensation_type: 'undisclosed',
    region_scope: 'not-stated',
    rights_disclosure: null,
    last_verified_at: secondCatalogExpansionVerifiedAt,
    published: true,
    description: 'Blind-reviewed literary magazine call accepting up to five previously unpublished comic pieces. Each piece must be under ten pages and supplied as high-resolution image files.',
    roles: ['artist', 'writer-artist', 'team'],
    formats: ['completed short comic'],
    requirements: [
      rule('grub-street-volume-76-comics', 'https://grubstreet.submittable.com/submit', 'Submission Guidelines', 'grub-unpublished', 'Only previously unpublished work, in print or online, is considered.', {
        kind: 'eligibility', field: 'previouslyPublished', operator: 'eq', value: false,
      }),
      rule('grub-street-volume-76-comics', 'https://grubstreet.submittable.com/submit', 'Comics guidelines', 'grub-pages', 'Each comic piece must be under ten pages.', {
        kind: 'eligibility', field: 'storyPages', operator: 'lte', value: 9,
      }),
      rule('grub-street-volume-76-comics', 'https://grubstreet.submittable.com/submit', 'Comics guidelines', 'grub-format', 'Prepare each comic as a PNG, TIFF, or high-quality JPEG file.', {
        kind: 'preparation', field: 'fileFormat', operator: 'in', value: ['png', 'tif', 'jpg'],
      }),
      rule('grub-street-volume-76-comics', 'https://grubstreet.submittable.com/submit', 'Comics guidelines', 'grub-dpi', 'Prepare comic files at 300 DPI or higher.', {
        kind: 'preparation', field: 'dpi', operator: 'gte', value: 300,
      }),
      rule('grub-street-volume-76-comics', 'https://grubstreet.submittable.com/submit', 'Comics guidelines', 'grub-dimensions', 'Each comic image must be at least 4 × 6 inches.', {
        kind: 'preparation', field: 'dimensionsReady', operator: 'eq', value: true,
      }),
      rule('grub-street-volume-76-comics', 'https://grubstreet.submittable.com/submit', 'Blind-review process', 'grub-blind', 'Remove identifying information from the work and its file name before submitting.'),
    ],
  },
  {
    id: 'anmly-graphic-narratives-2026-27',
    slug: 'anmly-graphic-narratives-2026-27',
    title: 'ANMLY graphic narratives',
    organizer: 'ANMLY',
    category: 'short-comic',
    official_url: 'https://anmly.org/calls/',
    status: 'open',
    deadline: null,
    deadline_timezone: null,
    deadline_date: '2027-02-01',
    deadline_note: 'Current reading period closes 1 February 2027; submission time and timezone not stated.',
    compensation: null,
    compensation_type: 'undisclosed',
    region_scope: 'not-stated',
    rights_disclosure: null,
    last_verified_at: secondCatalogExpansionVerifiedAt,
    published: true,
    description: 'Current reading period for challenging, previously unpublished comics and graphic narratives. ANMLY publishes work online and accepts graphic narratives during its general submission windows.',
    roles: ['artist', 'writer-artist', 'team'],
    formats: ['completed short comic'],
    requirements: [
      rule('anmly-graphic-narratives-2026-27', 'https://anmly.org/calls/', 'General Calls for Submissions', 'anmly-unpublished', 'The work must be previously unpublished, including on a personal blog.', {
        kind: 'eligibility', field: 'previouslyPublished', operator: 'eq', value: false,
      }),
      rule('anmly-graphic-narratives-2026-27', 'https://anmly.org/calls/', 'General Calls for Submissions', 'anmly-ai', 'AI-generated or AI-assisted writing and art are not accepted.', {
        kind: 'eligibility', field: 'aiUsed', operator: 'eq', value: false,
      }),
      rule('anmly-graphic-narratives-2026-27', 'https://anmly.org/calls/', 'General Calls for Submissions', 'anmly-fee', 'The standard submission fee is $3; the organizer provides a hardship waiver by email.'),
      rule('anmly-graphic-narratives-2026-27', 'https://anmly.org/calls/', 'General Calls for Submissions', 'anmly-fit', 'Review previous ANMLY issues to confirm that the graphic narrative fits the journal’s experimental and boundary-pushing focus.'),
    ],
  },
  {
    id: 'exposition-review-trip-comics',
    slug: 'exposition-review-trip-comics',
    title: 'Exposition Review Vol. XII — Trip comics',
    organizer: 'Exposition Review',
    category: 'short-comic',
    official_url: 'https://expositionreview.com/2026/09/call-for-submissions-for-vol-xii-trip/',
    status: 'open',
    deadline: null,
    deadline_timezone: null,
    deadline_date: '2026-12-15',
    deadline_note: '15 December 2026; submission time and timezone not stated.',
    compensation: 'Accepted work receives $50 USD (organizer’s stated terms).',
    compensation_type: 'paid',
    region_scope: 'not-stated',
    rights_disclosure: 'The creator retains copyright and is asked to credit Exposition Review if the work is republished.',
    last_verified_at: thirdCatalogExpansionVerifiedAt,
    published: true,
    description: 'Themed literary-journal call for self-contained comics responding to “Trip,” including journeys, interruptions, altered states, and transformative stumbles.',
    roles: ['artist', 'writer-artist', 'team'],
    formats: ['completed short comic'],
    requirements: [
      rule('exposition-review-trip-comics', 'https://expositionreview.com/submission-guidelines/', 'Additional information', 'expo-unpublished', 'Submit only previously unpublished work, including work that has not appeared online.', {
        kind: 'eligibility', field: 'previouslyPublished', operator: 'eq', value: false,
      }),
      rule('exposition-review-trip-comics', 'https://expositionreview.com/submission-guidelines/', 'Comics', 'expo-pages', 'Each comic must be self-contained and no longer than three pages.', {
        kind: 'eligibility', field: 'storyPages', operator: 'lte', value: 3,
      }),
      rule('exposition-review-trip-comics', 'https://expositionreview.com/submission-guidelines/', 'Additional information', 'expo-bio', 'Prepare a cover letter with contact information and a brief biography.', {
        kind: 'preparation', field: 'bio', operator: 'eq', value: true,
      }),
      rule('exposition-review-trip-comics', 'https://expositionreview.com/submission-guidelines/', 'Comics', 'expo-piece-count', 'A single submission may contain no more than three comic pieces.'),
      rule('exposition-review-trip-comics', 'https://expositionreview.com/2026/09/call-for-submissions-for-vol-xii-trip/', 'Call for Submissions: Trip', 'expo-theme', 'Confirm that the comic responds to the “Trip” theme described by the editors.'),
    ],
  },
  {
    id: 'prism-general-comics-2026',
    slug: 'prism-general-comics-2026',
    title: 'PRISM international — general comics',
    organizer: 'PRISM international',
    category: 'short-comic',
    official_url: 'https://prismmagazine.ca/submit/',
    status: 'open',
    deadline: null,
    deadline_timezone: null,
    deadline_date: '2026-11-15',
    deadline_note: '15 November 2026; submission time and timezone not stated.',
    compensation: 'Comics are accepted in the prose category, which pays $40 CAD per printed page plus two contributor copies (organizer’s stated terms).',
    compensation_type: 'paid',
    region_scope: 'worldwide',
    rights_disclosure: 'PRISM purchases first North American serial rights (organizer’s stated terms).',
    last_verified_at: thirdCatalogExpansionVerifiedAt,
    published: true,
    description: 'International literary magazine reading period for original comics and other prose forms. The call is open to established and emerging creators worldwide, subject to UBC affiliation exclusions.',
    roles: ['artist', 'writer-artist', 'team'],
    formats: ['completed short comic'],
    requirements: [
      rule('prism-general-comics-2026', 'https://prismmagazine.ca/submit/', 'General submission guidelines', 'prism-submit-method', 'Submit through PRISM’s Submittable portal; email and postal submissions are not accepted except from incarcerated writers.'),
      rule('prism-general-comics-2026', 'https://prismmagazine.ca/submit/', 'General submission guidelines', 'prism-bio', 'Prepare a cover letter with full contact information and a biography of no more than 50 words that states where you live.', {
        kind: 'preparation', field: 'bio', operator: 'eq', value: true,
      }),
      rule('prism-general-comics-2026', 'https://prismmagazine.ca/submit/', 'Prose guidelines', 'prism-one-piece', 'Submit one piece at a time and wait for a response before submitting again.'),
      rule('prism-general-comics-2026', 'https://prismmagazine.ca/submit/', 'Eligibility notice', 'prism-ubc', 'Current and incoming UBC School of Creative Writing students and faculty are not eligible; alumni must also review the two-year course restriction.'),
      rule('prism-general-comics-2026', 'https://prismmagazine.ca/submit/', 'General submission guidelines', 'prism-fee', 'The standard reading fee is $3 CAD; an Inclusive Access option is available when the fee is prohibitive.'),
    ],
  },
  {
    id: 'tampa-review-graphic-narratives-2026',
    slug: 'tampa-review-graphic-narratives-2026',
    title: 'Tampa Review — graphic narratives',
    organizer: 'Tampa Review',
    category: 'short-comic',
    official_url: 'https://tampareview.org/submissions/',
    status: 'open',
    deadline: null,
    deadline_timezone: null,
    deadline_date: '2026-12-31',
    deadline_note: '31 December 2026; submission time and timezone not stated.',
    compensation: 'Work accepted for the print edition receives $10 USD per published page and one contributor copy; online-publication payment is not stated.',
    compensation_type: 'conditional',
    region_scope: 'worldwide',
    rights_disclosure: null,
    last_verified_at: thirdCatalogExpansionVerifiedAt,
    published: true,
    description: 'University of Tampa literary journal call for previously unpublished graphic narratives. General submissions and work for the “Florida Man” themed issue are both being considered.',
    roles: ['artist', 'writer-artist', 'team'],
    formats: ['completed short comic'],
    requirements: [
      rule('tampa-review-graphic-narratives-2026', 'https://tampareview.submittable.com/submit', 'Art Submissions', 'tampa-unpublished', 'The submitted graphic narrative must be previously unpublished.', {
        kind: 'eligibility', field: 'previouslyPublished', operator: 'eq', value: false,
      }),
      rule('tampa-review-graphic-narratives-2026', 'https://tampareview.submittable.com/submit', 'Art Submissions', 'tampa-ai', 'Work created with AI is not accepted.', {
        kind: 'eligibility', field: 'aiUsed', operator: 'eq', value: false,
      }),
      rule('tampa-review-graphic-narratives-2026', 'https://tampareview.submittable.com/submit', 'Art Submissions', 'tampa-format', 'Prepare TIFF, JPG, SVG, or PNG files; TIFF is preferred.', {
        kind: 'preparation', field: 'fileFormat', operator: 'in', value: ['tif', 'jpg', 'svg', 'png'],
      }),
      rule('tampa-review-graphic-narratives-2026', 'https://tampareview.submittable.com/submit', 'Art Submissions', 'tampa-dimensions', 'Prepare the work to fit within a 5 × 8.5 inch page area.', {
        kind: 'preparation', field: 'dimensionsReady', operator: 'eq', value: true,
      }),
      rule('tampa-review-graphic-narratives-2026', 'https://tampareview.submittable.com/submit', 'Art Submissions', 'tampa-pages', 'Print submissions should be no more than five graphic-narrative pages; longer work may be considered for the website.'),
      rule('tampa-review-graphic-narratives-2026', 'https://tampareview.org/submissions/', 'Special Issue', 'tampa-theme', 'If submitting for the “Florida Man” issue, identify that in the cover letter and review the theme guidance.'),
    ],
  },
  {
    id: 'arkansas-international-graphic-literature-2026',
    slug: 'arkansas-international-graphic-literature-2026',
    title: 'The Arkansas International — graphic literature',
    organizer: 'The Arkansas International',
    category: 'short-comic',
    official_url: 'https://acwlp.submittable.com/submit',
    status: 'open',
    deadline: null,
    deadline_timezone: null,
    deadline_date: '2026-10-15',
    deadline_note: '15 October 2026; submission time and timezone not stated.',
    compensation: null,
    compensation_type: 'undisclosed',
    region_scope: 'worldwide',
    rights_disclosure: null,
    last_verified_at: thirdCatalogExpansionVerifiedAt,
    published: true,
    description: 'International literary magazine call for short, previously unpublished comics in English or translation, with a portfolio link and brief cover letter.',
    roles: ['artist', 'writer-artist', 'team'],
    formats: ['completed short comic'],
    requirements: [
      rule('arkansas-international-graphic-literature-2026', 'https://acwlp.submittable.com/submit', 'General Submissions — Graphic Literature 2026', 'arkansas-unpublished', 'Submit only previously unpublished comics.', {
        kind: 'eligibility', field: 'previouslyPublished', operator: 'eq', value: false,
      }),
      rule('arkansas-international-graphic-literature-2026', 'https://www.arkint.org/creative-submissions', 'Creative Submissions general guidelines', 'arkansas-pages', 'A comics submission may contain no more than five pages.', {
        kind: 'eligibility', field: 'storyPages', operator: 'lte', value: 5,
      }),
      rule('arkansas-international-graphic-literature-2026', 'https://www.arkint.org/creative-submissions', 'Creative Submissions general guidelines', 'arkansas-portfolio', 'Include a link to the artist’s larger portfolio.', {
        kind: 'preparation', field: 'portfolio', operator: 'eq', value: true,
      }),
      rule('arkansas-international-graphic-literature-2026', 'https://acwlp.submittable.com/submit', 'Cover Letter Formatting', 'arkansas-bio', 'Prepare a cover letter with the work’s title, contact information, and a brief biography.', {
        kind: 'preparation', field: 'bio', operator: 'eq', value: true,
      }),
      rule('arkansas-international-graphic-literature-2026', 'https://acwlp.submittable.com/submit', 'General Submissions — Graphic Literature 2026', 'arkansas-one-piece', 'Submit no more than one piece while a decision is pending.'),
      rule('arkansas-international-graphic-literature-2026', 'https://acwlp.submittable.com/submit', 'General Submissions — Graphic Literature 2026', 'arkansas-fee', 'The standard submission fee is $4 USD; the organizer offers fee waivers for BIPOC creators and people who need financial assistance.'),
    ],
  },
  {
    id: 'mad-cave-creator-owned-submissions',
    slug: 'mad-cave-creator-owned-submissions',
    title: 'Creator-owned comic submissions',
    organizer: 'Mad Cave Studios',
    category: 'short-comic',
    official_url: 'https://madcavestudios.com/creators/',
    status: 'rolling',
    deadline: null,
    deadline_timezone: null,
    deadline_date: null,
    compensation: null,
    compensation_type: 'undisclosed',
    region_scope: 'not-stated',
    rights_disclosure:
      'The submission agreement states that review creates no contract or compensation obligation and requires applicants to warrant ownership and authority to submit. Read the complete agreement before submitting.',
    last_verified_at: fourthCatalogExpansionVerifiedAt,
    published: true,
    description:
      'Rolling creator-owned submissions for one-shots, mini-series, and original graphic novels across Mad Cave and its imprints. The online form requires a linked pitch PDF and sample art.',
    roles: ['writer', 'artist', 'writer-artist', 'team'],
    formats: ['pitch'],
    requirements: [
      rule('mad-cave-creator-owned-submissions', 'https://madcavestudios.com/creators/', 'Creator Owned Submission Form', 'mad-cave-age', 'Applicants must be at least 18 years old.', {
        kind: 'eligibility', field: 'age', operator: 'gte', value: 18,
      }),
      rule('mad-cave-creator-owned-submissions', 'https://madcavestudios.com/submission-agreement/', 'Submission Agreement', 'mad-cave-rights', 'You must own or control the rights needed to submit the project and disclose any collaborators or co-creators.', {
        kind: 'eligibility', field: 'rights', operator: 'eq', value: true,
      }),
      rule('mad-cave-creator-owned-submissions', 'https://madcavestudios.com/creators/', 'Creator Owned Submission Form', 'mad-cave-samples', 'Include 6–8 pages of comic art in the linked pitch PDF.', {
        kind: 'preparation', field: 'samplePages', operator: 'gte', value: 6,
      }),
      rule('mad-cave-creator-owned-submissions', 'https://madcavestudios.com/creators/', 'Creator Owned Submission Form', 'mad-cave-pdf', 'Prepare a pitch PDF that can be shared through an accessible link.', {
        kind: 'preparation', field: 'pdf', operator: 'eq', value: true,
      }),
      rule('mad-cave-creator-owned-submissions', 'https://madcavestudios.com/creators/', 'Creator Owned Submission Form', 'mad-cave-breakdown', 'Include a series breakdown in the pitch PDF.', {
        kind: 'preparation', field: 'synopsis', operator: 'eq', value: true,
      }),
      rule('mad-cave-creator-owned-submissions', 'https://madcavestudios.com/creators/', 'Creator Owned Submission Form', 'mad-cave-format', 'Choose the applicable format: one-shot, mini-series, or original graphic novel.'),
      rule('mad-cave-creator-owned-submissions', 'https://madcavestudios.com/submission-agreement/', 'Submission Agreement', 'mad-cave-agreement', 'Read the complete submission agreement before sending work; it contains the organizer’s terms for review, ownership warranties, disputes, and remedies.'),
    ],
  },
  {
    id: 'black-panel-press-submissions',
    slug: 'black-panel-press-submissions',
    title: 'Graphic novel and shorter-comic submissions',
    organizer: 'Black Panel Press',
    category: 'short-comic',
    official_url: 'https://blackpanelpress.com/pages/graphic-novel-submissions',
    status: 'rolling',
    deadline: null,
    deadline_timezone: null,
    deadline_date: null,
    compensation: 'The organizer states that published creators receive royalties; the rate and agreement terms are not disclosed on the submissions page.',
    compensation_type: 'conditional',
    region_scope: 'not-stated',
    rights_disclosure: 'The organizer states that creators maintain ownership of their copyright; confirm the complete contract terms before accepting an offer.',
    last_verified_at: fourthCatalogExpansionVerifiedAt,
    published: true,
    description:
      'Rolling submissions for graphic novels, shorter comics, and single issues. Completed work is preferred, and comics teams must already be assembled.',
    roles: ['writer', 'artist', 'writer-artist', 'team'],
    formats: ['pitch', 'completed short comic'],
    requirements: [
      rule('black-panel-press-submissions', 'https://blackpanelpress.com/pages/graphic-novel-submissions', 'Graphic Novel Submissions', 'black-panel-team', 'Writers and artists must submit with an assembled comics team; the publisher does not pair collaborators.', {
        kind: 'eligibility', roles: ['writer', 'artist'], field: 'collaborator', operator: 'eq', value: true,
      }),
      rule('black-panel-press-submissions', 'https://blackpanelpress.com/pages/graphic-novel-submissions', 'Graphic Novel Submissions', 'black-panel-samples', 'Include at least ten illustrated pages, preferably in color when applicable.', {
        kind: 'preparation', field: 'samplePages', operator: 'gte', value: 10,
      }),
      rule('black-panel-press-submissions', 'https://blackpanelpress.com/pages/graphic-novel-submissions', 'Graphic Novel Submissions', 'black-panel-pdf', 'Provide the complete work as a PDF when it is available, using an accessible link that does not expire.', {
        kind: 'preparation', field: 'pdf', operator: 'eq', value: true,
      }),
      rule('black-panel-press-submissions', 'https://blackpanelpress.com/pages/graphic-novel-submissions', 'Graphic Novel Submissions', 'black-panel-length', 'The publisher primarily seeks graphic novels of 60 or more pages but also considers shorter comics and single-issue projects.'),
      rule('black-panel-press-submissions', 'https://blackpanelpress.com/pages/graphic-novel-submissions', 'Graphic Novel Submissions', 'black-panel-genre', 'The publisher does not seek superhero stories, conventional commercial genre fiction, or work built mainly from familiar genre formulas.'),
    ],
  },
  {
    id: 'fantagraphics-comic-submissions',
    slug: 'fantagraphics-comic-submissions',
    title: 'Comic and graphic novel submissions',
    organizer: 'Fantagraphics',
    category: 'short-comic',
    official_url: 'https://www.fantagraphics.com/pages/submissions',
    status: 'rolling',
    deadline: null,
    deadline_timezone: null,
    deadline_date: null,
    compensation: null,
    compensation_type: 'undisclosed',
    region_scope: 'not-stated',
    rights_disclosure: null,
    last_verified_at: fourthCatalogExpansionVerifiedAt,
    published: true,
    description:
      'Rolling submissions for independently created comics and graphic novels. The publisher requests substantial finished sequential art, a synopsis, and the projected final length.',
    roles: ['writer', 'artist', 'writer-artist', 'team'],
    formats: ['pitch', 'completed short comic'],
    requirements: [
      rule('fantagraphics-comic-submissions', 'https://www.fantagraphics.com/pages/submissions', 'What should I submit?', 'fantagraphics-samples', 'Submit at least 20 pages of completed sequential art as high-quality reproductions; do not send original artwork.', {
        kind: 'preparation', field: 'samplePages', operator: 'gte', value: 20,
      }),
      rule('fantagraphics-comic-submissions', 'https://www.fantagraphics.com/pages/submissions', 'What should I submit?', 'fantagraphics-synopsis', 'Include a synopsis of the complete storyline.', {
        kind: 'preparation', field: 'synopsis', operator: 'eq', value: true,
      }),
      rule('fantagraphics-comic-submissions', 'https://www.fantagraphics.com/pages/submissions', 'Creative team guidance', 'fantagraphics-team', 'Creators limited to one production role must assemble their own team; the publisher does not pair collaborators.', {
        kind: 'eligibility', roles: ['writer', 'artist'], field: 'collaborator', operator: 'eq', value: true,
      }),
      rule('fantagraphics-comic-submissions', 'https://www.fantagraphics.com/pages/submissions', 'What should I submit?', 'fantagraphics-length', 'State the projected final page count; the publisher does not prescribe a standard format or page length.'),
      rule('fantagraphics-comic-submissions', 'https://www.fantagraphics.com/pages/submissions', 'How and where should I send my submission?', 'fantagraphics-cover-letter', 'Include a cover letter with your name and mailing address; a résumé is not required.'),
      rule('fantagraphics-comic-submissions', 'https://www.fantagraphics.com/pages/submissions', 'Editorial focus', 'fantagraphics-focus', 'Review the publisher’s editorial focus before submitting; it says mainstream superhero, vigilante, horror, fantasy, and science-fiction pitches are rarely a fit.'),
    ],
  },
];

const fixtureSource = '/development-guidelines';
export const developmentCall: Opportunity = {
  id: 'dev-anthology',
  slug: 'development-anthology',
  title: 'Practice anthology',
  organizer: 'ComicReady development fixture',
  category: 'anthology',
  official_url: fixtureSource,
  status: 'open',
  deadline: null,
  deadline_timezone: null,
  deadline_date: null,
  compensation: null,
  compensation_type: 'undisclosed',
  region_scope: 'not-stated',
  rights_disclosure: null,
  last_verified_at: null,
  published: true,
  fixture: true,
  description: 'A fictional call for testing the checker. Not an opportunity and not accepting applications.',
  roles: ['writer', 'artist', 'writer-artist', 'team'],
  formats: ['pitch', 'completed short comic'],
  requirements: [
    rule('dev-anthology', fixtureSource, 'Development rule A', 'dev-rights', 'You must control the rights needed to submit.', {
      kind: 'eligibility',
      field: 'rights',
      operator: 'eq',
      value: true,
    }),
    rule('dev-anthology', fixtureSource, 'Development rule B', 'dev-team', 'Writers must have an artist collaborator.', {
      kind: 'eligibility',
      roles: ['writer'],
      field: 'collaborator',
      operator: 'eq',
      value: true,
    }),
    rule(
      'dev-anthology',
      fixtureSource,
      'Development rule C',
      'dev-samples',
      'Prepare at least three completed sequential sample pages.',
      { kind: 'preparation', field: 'samplePages', operator: 'gte', value: 3 },
    ),
    rule(
      'dev-anthology',
      fixtureSource,
      'Development rule D',
      'dev-length',
      'The proposed story must be no more than eight pages.',
      { kind: 'eligibility', field: 'storyPages', operator: 'lte', value: 8 },
    ),
    rule('dev-anthology', fixtureSource, 'Development rule E', 'dev-pdf', 'Prepare a submission PDF.', {
      kind: 'preparation',
      field: 'pdf',
      operator: 'eq',
      value: true,
    }),
  ],
};
