import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {afterAll,beforeAll,expect,test} from 'vitest';
const db=new PGlite();
const admin='10000000-0000-4000-8000-000000000001';
const user='10000000-0000-4000-8000-000000000002';
const id='20000000-0000-4000-8000-000000000001';
const doc={id,slug:'test-call',title:'Test',organizer:'Organizer',category:'anthology',official_url:'https://example.com',status:'open',deadline:null,deadline_timezone:null,compensation:null,rights_disclosure:null,description:'A test only',roles:['writer'],formats:['script'],published:false};
const rule={id:'30000000-0000-4000-8000-000000000001',opportunity_id:id,kind:'preparation',roles:[],formats:[],field:'script',operator:'eq',value:true,wording:'Prepare script',source_reference:'Guidelines',source_url:'https://example.com'};
async function role(who:'anon'|'authenticated',uid:string=''){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);await db.exec('set role '+who);}
async function save(published=false,verified=false,rules:unknown[]=[rule]){return db.query('select public.save_opportunity($1::jsonb,$2::jsonb,$3,$4)',[JSON.stringify({...doc,published}),JSON.stringify(rules),verified,'test']);}
beforeAll(async()=>{await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to anon,authenticated;insert into auth.users values('${admin}'),('${user}');`);for(const migration of ['202609300001_core.sql','202609300002_measurement.sql','202609300003_date_only_deadlines.sql','202609300004_catalog_discovery.sql','202609300005_checker_fields.sql','202610010001_verification_queue.sql','202610030002_admin_analytics.sql'])await db.exec(readFileSync('supabase/migrations/'+migration,'utf8'));await db.query('insert into public.admin_users values($1)',[admin]);},30000);
afterAll(async()=>{await db.close();});
test('ordinary account cannot grant itself admin or save calls',async()=>{await role('authenticated',user);expect((await db.query('select public.is_admin() as ok')).rows).toEqual([{ok:false}]);await expect(db.query('insert into public.admin_users values($1)',[user])).rejects.toThrow();await expect(save()).rejects.toThrow(/Admin access/);});
test('admin draft and its rules are invisible to public and ordinary users',async()=>{await role('authenticated',admin);await save();for(const who of ['anon','authenticated'] as const){await role(who,user);expect((await db.query('select * from public.opportunities')).rows).toHaveLength(0);expect((await db.query('select * from public.requirements')).rows).toHaveLength(0);}await role('anon');await expect(db.query("update public.opportunities set title='bad'" )).rejects.toThrow();});
test('publishing requires verification; verified call becomes readable',async()=>{await role('authenticated',admin);await expect(save(true,false)).rejects.toThrow(/Review guidelines/);await save(true,true);await role('anon');expect((await db.query('select * from public.opportunities')).rows).toHaveLength(1);expect((await db.query('select * from public.requirements')).rows).toHaveLength(1);await expect(db.query('select * from public.verification_events')).rejects.toThrow();});
test('bad rule save rolls back without losing published content',async()=>{await role('authenticated',admin);await expect(save(false,false,[{...rule,source_url:'javascript:alert(1)'}])).rejects.toThrow();const row=(await db.query<{published:boolean;last_verified_at:string|null}>('select published,last_verified_at from public.opportunities')).rows[0];expect(row.published).toBe(true);expect(row.last_verified_at).not.toBeNull();expect((await db.query('select * from public.requirements')).rows).toHaveLength(1);});
test('editing without re-verification unpublishes and hides nested rules',async()=>{await role('authenticated',admin);await save(false,false);await role('anon');expect((await db.query('select * from public.opportunities')).rows).toHaveLength(0);expect((await db.query('select * from public.requirements')).rows).toHaveLength(0);});

test('public events only count published calls and remain private',async()=>{await role('anon');await expect(db.query("select public.record_product_event('opportunity_viewed','test-call')")).rejects.toThrow(/Published call/);await role('authenticated',admin);await save(true,true);await role('anon');await db.query("select public.record_product_event('opportunity_viewed','test-call')");await db.query("select public.record_product_event('opportunity_viewed','test-call')");await expect(db.query("select public.record_product_event('arbitrary','test-call')")).rejects.toThrow(/Unknown event/);await expect(db.query('select * from public.event_counts')).rejects.toThrow();await role('authenticated',user);expect((await db.query('select * from public.event_counts')).rows).toHaveLength(0);await role('authenticated',admin);expect((await db.query("select count from public.event_counts where event='opportunity_viewed'")).rows).toEqual([{count:2}]);});
test('public page views accept known pages without creating visitor profiles',async()=>{await role('anon');await db.query("select public.record_product_event('page_viewed','home')");await db.query("select public.record_product_event('page_viewed','catalog')");await expect(db.query("select public.record_product_event('page_viewed','private-page')")).rejects.toThrow(/Unknown page/);await role('authenticated',admin);expect((await db.query("select call_slug,count from public.event_counts where event='page_viewed' order by call_slug")).rows).toEqual([{call_slug:'catalog',count:1},{call_slug:'home',count:1}]);});
test('corrections stay private and increment the aggregate',async()=>{await role('anon');await db.query("select public.submit_correction('test-call','The official deadline has changed.')");await expect(db.query('select * from public.corrections')).rejects.toThrow();await role('authenticated',user);expect((await db.query('select * from public.corrections')).rows).toHaveLength(0);await role('authenticated',admin);expect((await db.query('select * from public.corrections')).rows).toHaveLength(1);expect((await db.query("select count from public.event_counts where event='correction_submitted'")).rows).toEqual([{count:1}]);});
test('only an admin can record an audited verification recheck',async()=>{await role('authenticated',admin);await expect(db.query('select public.verify_opportunity($1,$2)',[id,''])).rejects.toThrow(/note/i);await db.query('select public.verify_opportunity($1,$2)',[id,'Checked deadline, payment, rights, and all sourced rules.']);const opportunity=(await db.query<{last_verified_at:string|null}>('select last_verified_at from public.opportunities where id=$1',[id])).rows[0];expect(opportunity.last_verified_at).not.toBeNull();expect((await db.query("select admin_note from public.verification_events where opportunity_id=$1 and result='verified' order by id desc limit 1",[id])).rows).toEqual([{admin_note:'Checked deadline, payment, rights, and all sourced rules.'}]);await role('authenticated',user);await expect(db.query('select public.verify_opportunity($1,$2)',[id,'Unauthorized check'])).rejects.toThrow(/Admin access/);});
