import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getOpportunity } from '@/lib/opportunities';
import { effectiveStatus, verificationLabel, UNKNOWN } from '@/lib/model';
export const dynamic='force-dynamic';
export default async function Detail({params}:{params:Promise<{slug:string}>}){
 const c=await getOpportunity((await params).slug);if(!c)notFound();
 return <section className="page-section"><Link className="text-link" href="/opportunities">← All calls</Link><p className="eyebrow section-gap">{c.fixture?'DEVELOPMENT FIXTURE':c.organizer} / {effectiveStatus(c).toUpperCase()}</p><h1 className="page-title">{c.title}</h1><p className="page-intro">{c.description}</p>{c.fixture&&<p className="notice">Fictional testing data. This is not an actual call and does not accept submissions.</p>}<div className="detail-grid"><div><h2 className="section-title">The published requirements</h2>{c.requirements.map(r=><article key={r.id} className="requirement"><p className="eyebrow">{r.roles.length?r.roles.join(' / '):'ALL APPLICANTS'}{r.formats.length?' · '+r.formats.join(' / '):''}</p><h3>{r.wording}</h3><a href={r.source_url}>{c.fixture?'Development source':r.source_reference} ↗</a></article>)}<Link className="button" href={"/check/"+c.slug}>Check my project →</Link></div><aside className="summary-box"><h2 className="section-title">Before you submit</h2><dl className="facts"><div><dt>Deadline</dt><dd>{c.deadline?verificationLabel(c.deadline):UNKNOWN}{c.deadline_timezone&&' · '+c.deadline_timezone}</dd></div><div><dt>Payment</dt><dd>{c.compensation||'Payment not disclosed; confirm with organizer.'}</dd></div><div><dt>Copyright & licensing</dt><dd>{c.rights_disclosure||UNKNOWN}</dd></div><div><dt>Manually verified</dt><dd>{verificationLabel(c.last_verified_at)}</dd></div></dl><a className="button" href={c.official_url}>{c.fixture?'Read fixture guidelines':'Official guidelines'} ↗</a><p className="muted">Apply through the organizer. ComicReady never accepts comic submissions.</p></aside></div></section>;
}
