'use client';
import {useActionState,useState} from 'react';
import Link from 'next/link';
import {ProjectForm} from './project-form';
import {saveCall} from '@/app/thgizcblljqbah/actions';
import {ADMIN_PATH} from '@/lib/admin-route';
import {roles,formats,fields,type Opportunity,type Requirement} from '@/lib/model';
const empty=():Opportunity=>({id:crypto.randomUUID(),slug:'',title:'',organizer:'',description:'',category:'anthology',official_url:'',status:'unknown',deadline:null,deadline_timezone:null,deadline_note:null,deadline_date:null,compensation:null,compensation_type:'undisclosed',region_scope:'not-stated',rights_disclosure:null,last_verified_at:null,published:false,roles:[],formats:[],requirements:[]});
export function AdminEditor({initial}:{initial?:Opportunity}){
 const [doc,setDoc]=useState<Opportunity>(()=>initial||empty());const [state,action,pending]=useActionState(saveCall,{});const [preview,setPreview]=useState(false);
 const patch=(key:string,value:unknown)=>setDoc(d=>({...d,[key]:value}));
 const updateRule=(id:string,change:Partial<Requirement>)=>setDoc(d=>({...d,requirements:d.requirements.map(r=>r.id===id?{...r,...change}:r)}));
 function addRule(){setDoc(d=>({...d,requirements:[...d.requirements,{id:crypto.randomUUID(),opportunity_id:d.id,kind:'review',roles:[],formats:[],field:null,operator:'review',value:null,wording:'',source_reference:'',source_url:d.official_url}]}));}
 return <><Link href={ADMIN_PATH}>← All admin calls</Link><form action={action} className="form-stack admin-form"><input type="hidden" name="payload" value={JSON.stringify(doc)}/><div className="form-grid">{(['title','slug','organizer','official_url'] as const).map(k=><label key={k}>{({title:'Title',slug:'URL slug',organizer:'Organizer',official_url:'Official HTTPS guidelines URL'})[k]}<input required value={doc[k]} onChange={e=>patch(k,e.target.value)}/></label>)}<label>Category<select value={doc.category} onChange={e=>patch('category',e.target.value)}><option>anthology</option><option>short-comic</option></select></label><label>Call status<select value={doc.status} onChange={e=>patch('status',e.target.value)}>{['unknown','open','rolling','closed'].map(s=><option key={s}>{s}</option>)}</select></label><label>Exact deadline (ISO timestamp with offset)<input placeholder="2026-12-01T23:59:00-05:00" value={doc.deadline||''} onChange={e=>patch('deadline',e.target.value||null)}/></label><label>Published deadline timezone<input placeholder="e.g. America/New_York" value={doc.deadline_timezone||''} onChange={e=>patch('deadline_timezone',e.target.value||null)}/></label><label>Published deadline date<input type="date" value={doc.deadline_date||''} onChange={e=>patch('deadline_date',e.target.value||null)}/></label><label>Date-only deadline note<input placeholder="15 October 2026; time and timezone not stated." value={doc.deadline_note||''} onChange={e=>patch('deadline_note',e.target.value||null)}/></label><label>Payment category<select value={doc.compensation_type||'undisclosed'} onChange={e=>patch('compensation_type',e.target.value)}>{['paid','conditional','unpaid','undisclosed'].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label>Region scope<select value={doc.region_scope||'not-stated'} onChange={e=>patch('region_scope',e.target.value)}><option value="worldwide">Worldwide</option><option value="restricted">Region restricted</option><option value="not-stated">Not stated</option></select></label></div>
 {(['description','compensation','rights_disclosure'] as const).map(k=><label key={k}>{({description:'Description',compensation:'Payment disclosure (blank = undisclosed)',rights_disclosure:'Copyright / licensing summary (blank = unknown)'})[k]}<textarea required={k==='description'} value={doc[k]||''} onChange={e=>patch(k,e.target.value||null)}/></label>)}
 <div className="form-grid"><fieldset><legend>Listing roles</legend>{roles.map(r=><label className="check-label" key={r}><input type="checkbox" checked={doc.roles.includes(r)} onChange={e=>patch('roles',e.target.checked?[...doc.roles,r]:doc.roles.filter(v=>v!==r))}/>{r}</label>)}</fieldset><fieldset><legend>Listing formats</legend>{formats.map(f=><label className="check-label" key={f}><input type="checkbox" checked={doc.formats.includes(f)} onChange={e=>patch('formats',e.target.checked?[...doc.formats,f]:doc.formats.filter(v=>v!==f))}/>{f}</label>)}</fieldset></div>
 <h2 className="section-title">Reviewed requirements</h2><p>Use “review” for nuanced language or exceptions. Listing filters do not become eligibility rules automatically. To restrict a role or format, enter an explicit sourced rule for that field.</p>
 {doc.requirements.map((r,index)=><fieldset key={r.id} className="rule-editor"><legend>Requirement {index+1}</legend><label>User-facing wording<textarea required value={r.wording} onChange={e=>updateRule(r.id,{wording:e.target.value})}/></label><div className="form-grid"><label>Outcome when unmet<select value={r.kind} onChange={e=>updateRule(r.id,{kind:e.target.value as Requirement['kind']})}><option value="review">Confirm with organizer</option><option value="eligibility">Not eligible</option><option value="preparation">Item to prepare</option></select></label><label>Comparison<select value={r.operator} onChange={e=>updateRule(r.id,{operator:e.target.value as Requirement['operator'],value:null})}>{['review','eq','gte','lte','in'].map(o=><option key={o}>{o}</option>)}</select></label><label>Project field<select value={r.field||''} onChange={e=>updateRule(r.id,{field:e.target.value as Requirement['field']||null})}><option value="">None (human review)</option>{fields.map(f=><option key={f}>{f}</option>)}</select></label><label>Expected value (JSON)<input key={r.operator+r.id} defaultValue={JSON.stringify(r.value)} placeholder={'true, 3, or ["US","CA"]'} onBlur={e=>{try{updateRule(r.id,{value:JSON.parse(e.target.value)});e.target.setCustomValidity('');}catch{e.target.setCustomValidity('Enter valid JSON, such as true, 3, or ["US"].');}}}/></label><label>Official source URL<input required type="url" value={r.source_url} onChange={e=>updateRule(r.id,{source_url:e.target.value})}/></label><label>Source section or short excerpt<input required value={r.source_reference} onChange={e=>updateRule(r.id,{source_reference:e.target.value})}/></label></div><div className="form-grid"><fieldset><legend>Apply to roles (none = all)</legend>{roles.map(role=><label className="check-label" key={role}><input type="checkbox" checked={r.roles.includes(role)} onChange={e=>updateRule(r.id,{roles:e.target.checked?[...r.roles,role]:r.roles.filter(v=>v!==role)})}/>{role}</label>)}</fieldset><fieldset><legend>Apply to formats (none = all)</legend>{formats.map(f=><label className="check-label" key={f}><input type="checkbox" checked={r.formats.includes(f)} onChange={e=>updateRule(r.id,{formats:e.target.checked?[...r.formats,f]:r.formats.filter(v=>v!==f)})}/>{f}</label>)}</fieldset></div><button type="button" className="text-button" onClick={()=>patch('requirements',doc.requirements.filter(v=>v.id!==r.id))}>Remove requirement</button></fieldset>)}
 <button className="button secondary" type="button" onClick={addRule}>Add requirement +</button><button className="button secondary" type="button" onClick={()=>setPreview(!preview)}>{preview?'Hide':'Review'} listing preview</button>
 {preview&&<article className="summary-box"><p className="eyebrow">PRIVATE PREVIEW / NOT PUBLISHED</p><h2>{doc.title||'Untitled call'}</h2><p>{doc.description}</p><p>{doc.compensation||'Payment not disclosed; confirm with organizer.'}</p><p>{doc.rights_disclosure||'Cannot determine from published guidelines'}</p>{doc.requirements.map(r=><p key={r.id}>{r.wording} — <a href={r.source_url}>Source</a></p>)}</article>}
 <label>Verification note<textarea name="note" maxLength={2000}/></label><label className="check-label"><input type="checkbox" name="verified"/>I have reviewed the current official guidelines and checked every rule and disclosure.</label><label className="check-label"><input type="checkbox" checked={doc.published} onChange={e=>patch('published',e.target.checked)}/>Publish this call (uncheck to unpublish)</label><p className="muted">Saving changes resets verification unless the review box is checked. Verification time is recorded by the database.</p>{state.error&&<p role="alert" className="error-message">{state.error}</p>}{state.success&&<p role="status" className="success-message">{state.success} <Link href={ADMIN_PATH+'/'+state.id}>Open saved record</Link></p>}<button className="button" disabled={pending}>{pending?'Saving…':'Save call and requirements'}</button></form>{preview&&<section className="section-gap"><h2 className="section-title">Try the draft’s fit results</h2><ProjectForm key={JSON.stringify(doc.requirements)} call={doc} preview/></section>}</>;
}
