'use client';
import { useState } from 'react';
import Link from 'next/link';
import { effectiveStatus, roles, verificationLabel, type Opportunity } from '@/lib/model';
export function OpportunityList({ calls }: { calls: Opportunity[] }) {
  const [query,setQuery]=useState(''); const [role,setRole]=useState(''); const [status,setStatus]=useState(''); const [category,setCategory]=useState('');
  const shown=calls.filter(c=>(c.title+' '+c.organizer+' '+c.description).toLowerCase().includes(query.toLowerCase())&&(!role||c.roles.includes(role as typeof roles[number]))&&(!status||effectiveStatus(c)===status)&&(!category||c.category===category));
  return <><div className="filters"><label>Search calls<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Title or organizer" /></label><label>Creator role<select value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['open','rolling','closed','unknown'].map(s=><option key={s}>{s}</option>)}</select></label><label>Call type<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All types</option><option>anthology</option><option>short-comic</option></select></label></div>
  <p className="eyebrow" role="status">{shown.length} {shown.length===1?'CALL':'CALLS'} SHOWN</p><div className="call-grid">{shown.map(c=><article className="call-card" key={c.id}><div className="panel-label"><span>{c.fixture?'DEVELOPMENT FIXTURE':c.category.toUpperCase()}</span><span>{effectiveStatus(c).toUpperCase()}</span></div><p className="muted">{c.organizer}</p><h2><Link href={'/opportunities/'+c.slug}>{c.title} <span aria-hidden="true">↗</span></Link></h2><p>{c.description}</p><dl className="facts"><div><dt>Deadline</dt><dd>{c.deadline?verificationLabel(c.deadline):'No deadline published; confirm with organizer.'}</dd></div><div><dt>Payment</dt><dd>{c.compensation||'Payment not disclosed; confirm with organizer.'}</dd></div></dl><p className="verification">{c.fixture?'Fictional example — not verified':`Manually checked: ${verificationLabel(c.last_verified_at)}`}</p><Link className="text-link" href={'/opportunities/'+c.slug}>Read requirements →</Link></article>)}</div>{!shown.length&&<div className="empty-state"><h2>No matching calls.</h2><p>Try a broader search or clear your filters.</p><button className="button" onClick={()=>{setQuery('');setRole('');setStatus('');setCategory('');}}>Clear filters</button></div>}</>;
}
