'use client';
import {useState,type FormEvent} from 'react';
import {track} from '@/lib/measurement';
import {useRouter} from 'next/navigation';
import {roles,formats,type Field,type Opportunity,type Project} from '@/lib/model';
import {relevantFields} from '@/lib/engine';
import {projectKey,readProject} from '@/lib/local-progress';
import {useHydrated} from './client-ready';
import {ResultsView} from './results-view';
const labels:Record<Field,string>={role:'Your creator role',format:'What are you submitting?',country:'Country of residence (two-letter code)',region:'Region of residence',rights:'Do you control the rights needed to submit?',samplePages:'Completed sequential sample pages',storyPages:'Total proposed story length / finished project pages',script:'Is a script ready?',synopsis:'Is a synopsis ready?',bio:'Is a creator bio ready?',portfolio:'Are examples of your work ready?',collaborator:'Do you have the required collaborator?',pdf:'Is the required submission file ready?'};
export function ProjectForm({call,preview=false}:{call:Opportunity;preview?:boolean}){const ready=useHydrated();return ready?<ProjectFormBody call={call} preview={preview}/>:<p role="status">Loading your project form…</p>;}
function ProjectFormBody({call,preview}:{call:Opportunity;preview:boolean}){
 const router=useRouter();const [project,setProject]=useState<Project>(()=>preview?{}:readProject(call.slug)||{});const [inline,setInline]=useState(false);const [storageError,setStorageError]=useState(false);const [checkedAt,setCheckedAt]=useState(0);
 const visible=relevantFields(call,project);
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setCheckedAt(Date.now());if(!preview&&!call.fixture)track('fit_check_completed',call.slug);if(preview){setInline(true);return;}
 try{localStorage.setItem(projectKey(call.slug),JSON.stringify(project));router.push('/results/'+call.slug);}catch{setStorageError(true);setInline(true);}}
 if(inline)return <><button className="text-button" onClick={()=>setInline(false)}>← Edit project answers</button>{storageError&&<p className="notice">Browser storage is unavailable. You can read and print this result here; it will not survive a reload.</p>}<ResultsView call={call} project={project} now={checkedAt} preview={preview} persist={!storageError&&!preview}/></>;
 return <form onSubmit={submit} className="form-stack"><p className="notice">{preview?'Private preview: answers are not saved.':'Your answers and checklist stay on this browser and device. No project facts or files are sent to ComicReady.'} Leave an answer unknown if you are unsure.</p>{visible.map((field,index)=>{const questionRules=call.requirements.filter(r=>r.field===field);return <div className="question" key={field}><label htmlFor={'project-'+field}><span className="eyebrow">{String(index+1).padStart(2,'0')} / PROJECT FACT</span>{labels[field]}</label>{field==='role'||field==='format'?<select id={'project-'+field} value={String(project[field]??'')} onChange={e=>setProject({...project,[field]:e.target.value||null})}><option value="">Not sure yet</option>{(field==='role'?roles:formats).map(v=><option key={v}>{v}</option>)}</select>:field==='samplePages'||field==='storyPages'?<><input id={'project-'+field} aria-describedby={field+'-help'} type="number" min="0" max="100000" step="1" placeholder="Unknown" value={project[field]===null||project[field]===undefined?'':String(project[field])} onChange={e=>setProject({...project,[field]:e.target.value===''?null:Number(e.target.value)})}/><p className="muted" id={field+'-help'}>{field==='samplePages'?'Count only completed sequential comic pages, not covers or pin-ups. Zero means none; blank means unknown.':'This is the whole story’s length, separate from completed sample pages. Blank means unknown.'}</p></>:field==='country'||field==='region'?<input id={'project-'+field} placeholder={field==='country'?'For example US or GB; blank if unknown':'Enter only if known'} maxLength={field==='country'?2:100} pattern={field==='country'?'[A-Za-z]{2}':undefined} value={String(project[field]??'')} onChange={e=>setProject({...project,[field]:e.target.value||null})}/>:<select id={'project-'+field} value={project[field]===true?'yes':project[field]===false?'no':''} onChange={e=>setProject({...project,[field]:e.target.value==='yes'?true:e.target.value==='no'?false:null})}><option value="">Not sure yet</option><option value="yes">Yes</option><option value="no">No</option></select>}{questionRules.map(r=><p className="question-source" key={r.id}>{r.wording} <a href={r.source_url}>{call.fixture?'Fixture source':'Official source'}</a></p>)}</div>;})}<button className="button">{preview?'Preview fit findings':'Check my project'} →</button><p className="muted">This checks published requirements, not artistic quality or likelihood of acceptance.</p></form>;
}
