-- Generated by scripts/generate-reviewed-catalog-migration.mjs.
-- Every row below comes from a manually reviewed official source in src/lib/catalog.ts.
-- Re-running this migration content is safe: calls are matched by slug and rules are replaced atomically.
do $migration$
declare
  catalog jsonb := $catalog$[
  {
    "id": "1b36efe6-5028-526e-ac1c-8a0dd7c2e6d0",
    "slug": "sector-13",
    "title": "Sector 13",
    "organizer": "Box of Rain / Sector House 13",
    "category": "anthology",
    "official_url": "https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/",
    "status": "rolling",
    "deadline": null,
    "deadline_timezone": null,
    "deadline_date": null,
    "compensation": "Unpaid: the organizer states that contributors are not paid.",
    "compensation_type": "unpaid",
    "region_scope": "not-stated",
    "rights_disclosure": null,
    "last_verified_at": "2026-09-30T17:25:00Z",
    "published": true,
    "description": "Science-fiction comics fanzine seeking writers, sequential artists, and letterers. Recheck the organizer’s page before contacting them.",
    "roles": [
      "writer",
      "artist",
      "writer-artist",
      "letterer",
      "team"
    ],
    "formats": [
      "script",
      "portfolio"
    ],
    "requirements": [
      {
        "id": "cf850816-53fa-5ed0-877c-4158218a9188",
        "opportunity_id": "1b36efe6-5028-526e-ac1c-8a0dd7c2e6d0",
        "kind": "review",
        "roles": [
          "writer",
          "writer-artist"
        ],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Have a script or story idea ready to share.",
        "source_reference": "Sector 13 contributor guidelines",
        "source_url": "https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/"
      },
      {
        "id": "d66e3586-c4c6-56bc-81d6-c882f1a7b6a0",
        "opportunity_id": "1b36efe6-5028-526e-ac1c-8a0dd7c2e6d0",
        "kind": "preparation",
        "roles": [
          "artist",
          "letterer",
          "writer-artist"
        ],
        "formats": [],
        "field": "portfolio",
        "operator": "eq",
        "value": true,
        "wording": "Provide examples of your comics or lettering work.",
        "source_reference": "Sector 13 contributor guidelines",
        "source_url": "https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/"
      },
      {
        "id": "d56d12a1-a1f2-5759-819d-d34e236f7c13",
        "opportunity_id": "1b36efe6-5028-526e-ac1c-8a0dd7c2e6d0",
        "kind": "review",
        "roles": [
          "writer",
          "writer-artist",
          "team"
        ],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Stories are generally up to seven pages; longer work may be considered. Confirm exceptions with the organizer.",
        "source_reference": "Sector 13 contributor guidelines",
        "source_url": "https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/"
      },
      {
        "id": "9cef2b77-a5ea-5c1d-8b08-98123de87580",
        "opportunity_id": "1b36efe6-5028-526e-ac1c-8a0dd7c2e6d0",
        "kind": "review",
        "roles": [],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Review the science-fiction/fantasy focus, audience guidance, and character restrictions with the organizer.",
        "source_reference": "Sector 13 contributor guidelines",
        "source_url": "https://www.boxofrainmag.co.uk/submission-guidelines/sector-13/"
      }
    ]
  },
  {
    "id": "f8a81089-4206-5bc6-bad7-ce65e33c30b6",
    "slug": "cbk-cba-v76",
    "title": "CBA vol 76 — World Without Pictures",
    "organizer": "CBK Comics",
    "category": "anthology",
    "official_url": "https://cbkcomics.com/submissions/",
    "status": "open",
    "deadline": "2027-02-15T22:59:59Z",
    "deadline_timezone": "Europe/Stockholm",
    "deadline_date": "2027-02-15",
    "compensation": "No guaranteed fee; surplus after costs may be shared. Published contributors receive five complimentary copies (organizer’s stated terms).",
    "compensation_type": "conditional",
    "region_scope": "not-stated",
    "rights_disclosure": "Copyright for submitted material remains with the creator (organizer’s stated terms).",
    "last_verified_at": "2026-09-30T17:25:00Z",
    "published": true,
    "description": "Experimental comics and texts for CBK’s anthology series. English-language work; high-resolution print files. Recheck the submissions page before sending.",
    "roles": [
      "writer",
      "writer-artist",
      "artist",
      "team"
    ],
    "formats": [
      "completed short comic",
      "script"
    ],
    "requirements": [
      {
        "id": "8b7abf54-0824-54c7-8f52-4a1a3b9c58ea",
        "opportunity_id": "f8a81089-4206-5bc6-bad7-ce65e33c30b6",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "english",
        "operator": "eq",
        "value": true,
        "wording": "Comics and texts should be in English.",
        "source_reference": "CBK submissions guidelines",
        "source_url": "https://cbkcomics.com/submissions/"
      },
      {
        "id": "2bd86391-2a6d-5a7c-b327-0e5326cfbee2",
        "opportunity_id": "f8a81089-4206-5bc6-bad7-ce65e33c30b6",
        "kind": "review",
        "roles": [
          "writer-artist",
          "artist",
          "team"
        ],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Comics are often about 5–30 pages, but other lengths are welcome. Confirm fit for this volume.",
        "source_reference": "CBK submissions guidelines",
        "source_url": "https://cbkcomics.com/submissions/"
      },
      {
        "id": "7c41e532-0f3d-5ac4-a2e9-93b9f1833525",
        "opportunity_id": "f8a81089-4206-5bc6-bad7-ce65e33c30b6",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "bio",
        "operator": "eq",
        "value": true,
        "wording": "Prepare a short bio (about 500–700 characters) with one URL.",
        "source_reference": "CBK submissions guidelines",
        "source_url": "https://cbkcomics.com/submissions/"
      },
      {
        "id": "01ff03d4-e4b9-52c2-bb5b-950ea519c50b",
        "opportunity_id": "f8a81089-4206-5bc6-bad7-ce65e33c30b6",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "fileFormat",
        "operator": "in",
        "value": [
          "tif"
        ],
        "wording": "Prepare the high-resolution print artwork as .TIF files with bleed.",
        "source_reference": "CBK submissions guidelines",
        "source_url": "https://cbkcomics.com/submissions/"
      },
      {
        "id": "2bde5455-96ac-5185-9465-7f291c7cac79",
        "opportunity_id": "f8a81089-4206-5bc6-bad7-ce65e33c30b6",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "aiUsed",
        "operator": "eq",
        "value": false,
        "wording": "Submissions created using AI are not accepted.",
        "source_reference": "CBK submissions guidelines",
        "source_url": "https://cbkcomics.com/submissions/"
      }
    ]
  },
  {
    "id": "4dc547cc-a25e-5fc0-8258-27e49c61bf30",
    "slug": "discord-bite",
    "title": "Bite — bisexual erotic horror anthology",
    "organizer": "Discord Comics",
    "category": "anthology",
    "official_url": "https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/",
    "status": "open",
    "deadline": "2026-10-15T22:59:59Z",
    "deadline_timezone": "Europe/London",
    "deadline_date": "2026-10-15",
    "compensation": "Stated rates for writers and artists plus profit share after Kickstarter; payment tied to successful funding (see official page).",
    "compensation_type": "conditional",
    "region_scope": "not-stated",
    "rights_disclosure": "One year exclusive publishing rights, then creators may reuse work (organizer’s stated terms).",
    "last_verified_at": "2026-09-30T17:25:00Z",
    "published": true,
    "description": "Paranormal, mild-horror erotica exploring bisexual themes. Applications from writers, artists, and teams—finished pages not required at submission. 18+ only.",
    "roles": [
      "writer",
      "artist",
      "writer-artist",
      "team"
    ],
    "formats": [
      "pitch",
      "portfolio",
      "script"
    ],
    "requirements": [
      {
        "id": "a8e12cf3-86a6-5c6c-97ed-b5902d863cfd",
        "opportunity_id": "4dc547cc-a25e-5fc0-8258-27e49c61bf30",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "age",
        "operator": "gte",
        "value": 18,
        "wording": "Applicants must be 18 or older.",
        "source_reference": "Bite submission info",
        "source_url": "https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/"
      },
      {
        "id": "00475d8d-823b-58c3-8c4e-896923b11f5b",
        "opportunity_id": "4dc547cc-a25e-5fc0-8258-27e49c61bf30",
        "kind": "review",
        "roles": [
          "writer-artist",
          "team"
        ],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Finished anthology stories are intended to run about 11–21 pages. Confirm length expectations for your role.",
        "source_reference": "Bite submission info",
        "source_url": "https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/"
      },
      {
        "id": "551631c1-0f9a-5794-9aa7-4aaff83d86da",
        "opportunity_id": "4dc547cc-a25e-5fc0-8258-27e49c61bf30",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "portfolio",
        "operator": "eq",
        "value": true,
        "wording": "Submit examples of prior comic or script work plus a short pitch—not a finished comic.",
        "source_reference": "Bite submission info",
        "source_url": "https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/"
      },
      {
        "id": "0628afb8-9edb-58ef-bf61-00d3b253c88a",
        "opportunity_id": "4dc547cc-a25e-5fc0-8258-27e49c61bf30",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "aiUsed",
        "operator": "eq",
        "value": false,
        "wording": "AI-generated content is not accepted.",
        "source_reference": "Bite submission info",
        "source_url": "https://www.discordcomics.com/Shop/wordpress/bite-submissions-info/"
      }
    ]
  },
  {
    "id": "41fe6947-3fbc-503c-8873-33e8f14543e4",
    "slug": "icc-smut-peddler-baddies",
    "title": "Smut Peddler Presents: Baddies",
    "organizer": "Iron Circus Comics",
    "category": "anthology",
    "official_url": "https://ironcircus.com/smut-peddler-baddies/",
    "status": "open",
    "deadline": "2026-12-01T23:59:59Z",
    "deadline_timezone": "America/Chicago",
    "deadline_date": "2026-12-01",
    "compensation": "Paid participation for accepted contributors; rates and terms are stated on the project page and in contributor agreements.",
    "compensation_type": "paid",
    "region_scope": "not-stated",
    "rights_disclosure": "Universal first publication rights to Iron Circus for one year; general publication rights in perpetuity (organizer’s stated terms).",
    "last_verified_at": "2026-09-30T17:25:00Z",
    "published": true,
    "description": "Full-color erotic comics anthology about villains. Proposals with portfolio links—4–20 pages if accepted. 18+ only; recheck the official page before submitting.",
    "roles": [
      "writer",
      "artist",
      "writer-artist",
      "team"
    ],
    "formats": [
      "pitch",
      "portfolio"
    ],
    "requirements": [
      {
        "id": "0d289e3e-3756-50cb-91d0-37336fe2da89",
        "opportunity_id": "41fe6947-3fbc-503c-8873-33e8f14543e4",
        "kind": "review",
        "roles": [],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Submissions open 1 October through 1 December 2026 on the organizer’s form (see official page).",
        "source_reference": "Smut Peddler Baddies project page",
        "source_url": "https://ironcircus.com/smut-peddler-baddies/"
      },
      {
        "id": "54d5c4c6-0891-5dc2-bf66-90e26fca75ab",
        "opportunity_id": "41fe6947-3fbc-503c-8873-33e8f14543e4",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "portfolio",
        "operator": "eq",
        "value": true,
        "wording": "Prepare creator names and emails, story title, a beginning–middle–end summary, estimated page count (4–20), and portfolio links.",
        "source_reference": "Smut Peddler Baddies project page",
        "source_url": "https://ironcircus.com/smut-peddler-baddies/"
      },
      {
        "id": "e22d5d75-e824-54fe-98fe-10aa30553fb2",
        "opportunity_id": "41fe6947-3fbc-503c-8873-33e8f14543e4",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "age",
        "operator": "gte",
        "value": 18,
        "wording": "Applicants must be 18 or older because the anthology contains mature erotic content.",
        "source_reference": "Smut Peddler Baddies project page",
        "source_url": "https://ironcircus.com/smut-peddler-baddies/"
      }
    ]
  },
  {
    "id": "fbb794e3-34c2-55c4-970b-09977dfc5da3",
    "slug": "thirdbear-2027-singles",
    "title": "2027 standalone single-issue comics",
    "organizer": "ThirdBear Press",
    "category": "short-comic",
    "official_url": "https://thirdbearpress.com/submissions",
    "status": "open",
    "deadline": "2026-12-01T23:59:59Z",
    "deadline_timezone": "Europe/London",
    "deadline_date": "2026-12-01",
    "compensation": null,
    "compensation_type": "undisclosed",
    "region_scope": "restricted",
    "rights_disclosure": null,
    "last_verified_at": "2026-09-30T17:25:00Z",
    "published": true,
    "description": "ThirdBear Press plans 3–4 standalone 28–32 page comics from UK-based creators for the second half of 2027. Full guidelines appear on the submissions page when applications open—recheck before sending.",
    "roles": [
      "writer-artist",
      "artist",
      "writer",
      "team"
    ],
    "formats": [
      "pitch",
      "completed short comic",
      "portfolio"
    ],
    "requirements": [
      {
        "id": "dc32b613-f888-5681-aee1-7158d4d07bd7",
        "opportunity_id": "fbb794e3-34c2-55c4-970b-09977dfc5da3",
        "kind": "review",
        "roles": [],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Submissions run 1 October through 1 December 2026; confirm details on the organizer’s page when live.",
        "source_reference": "ThirdBear Press submissions page",
        "source_url": "https://thirdbearpress.com/submissions"
      },
      {
        "id": "77657093-ef0a-5253-b4ba-7d10dc565265",
        "opportunity_id": "fbb794e3-34c2-55c4-970b-09977dfc5da3",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "country",
        "operator": "in",
        "value": [
          "GB"
        ],
        "wording": "The call is for UK-based creators. Confirm eligibility with the organizer if your situation is unclear.",
        "source_reference": "ThirdBear Press submissions page",
        "source_url": "https://thirdbearpress.com/submissions"
      },
      {
        "id": "04f7326c-8b0e-59ff-8568-00a92ec46346",
        "opportunity_id": "fbb794e3-34c2-55c4-970b-09977dfc5da3",
        "kind": "review",
        "roles": [
          "writer-artist",
          "team"
        ],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Target format is a standalone single issue of about 28–32 pages. Confirm expectations on the official page.",
        "source_reference": "ThirdBear Press submissions page",
        "source_url": "https://thirdbearpress.com/submissions"
      }
    ]
  },
  {
    "id": "3169f1b0-ad76-5507-afac-33f9866ceb81",
    "slug": "birdseye-bebop",
    "title": "The BeBop anthology",
    "organizer": "Bird's Eye Comics",
    "category": "anthology",
    "official_url": "https://birdseyecomics.com/pages/submissions",
    "status": "rolling",
    "deadline": null,
    "deadline_timezone": null,
    "deadline_date": null,
    "compensation": "Page rates are negotiated per assignment; payment on completion (organizer’s stated terms).",
    "compensation_type": "paid",
    "region_scope": "not-stated",
    "rights_disclosure": "Artwork produced under assignment is company-owned (organizer’s stated terms).",
    "last_verified_at": "2026-09-30T17:25:00Z",
    "published": true,
    "description": "Ongoing anthology series accepting scripts and artist portfolios for current or future issues. Stories often run 1–20 pages. Recheck which issue is open before you pitch.",
    "roles": [
      "writer",
      "artist",
      "writer-artist",
      "colorist",
      "letterer",
      "team"
    ],
    "formats": [
      "script",
      "portfolio",
      "pitch"
    ],
    "requirements": [
      {
        "id": "6b0f0b2a-b419-5813-b8f8-cbf084f638a2",
        "opportunity_id": "3169f1b0-ad76-5507-afac-33f9866ceb81",
        "kind": "preparation",
        "roles": [
          "writer"
        ],
        "formats": [],
        "field": "script",
        "operator": "eq",
        "value": true,
        "wording": "Writers: send name, contact, experience, portfolio or samples, genre preferences, team details, and story plans to thebebop@birdseyecomics.com.",
        "source_reference": "Bird's Eye Comics submissions",
        "source_url": "https://birdseyecomics.com/pages/submissions"
      },
      {
        "id": "ea702bfd-7444-5265-97d7-fa86c7c011ee",
        "opportunity_id": "3169f1b0-ad76-5507-afac-33f9866ceb81",
        "kind": "preparation",
        "roles": [
          "artist",
          "colorist",
          "letterer"
        ],
        "formats": [],
        "field": "portfolio",
        "operator": "eq",
        "value": true,
        "wording": "Artists: include portfolio, experience, social links, preferred roles (inking, color, lettering, etc.), and rates when applying.",
        "source_reference": "Bird's Eye Comics submissions",
        "source_url": "https://birdseyecomics.com/pages/submissions"
      },
      {
        "id": "aefbb888-052d-5823-9edf-b0d880631c19",
        "opportunity_id": "3169f1b0-ad76-5507-afac-33f9866ceb81",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "rights",
        "operator": "eq",
        "value": true,
        "wording": "Only original content; the organizer states a no-tolerance policy for hate speech.",
        "source_reference": "Bird's Eye Comics submissions",
        "source_url": "https://birdseyecomics.com/pages/submissions"
      }
    ]
  },
  {
    "id": "8a94fc98-65bb-558e-af5e-8344e0e8dcf8",
    "slug": "kkum-hybrid-horror",
    "title": "Hybrid Horror Anthology",
    "organizer": "KKUM",
    "category": "anthology",
    "official_url": "https://www.kkum.org/",
    "status": "open",
    "deadline": null,
    "deadline_timezone": null,
    "deadline_note": "15 October 2026; submission time and timezone not stated.",
    "deadline_date": "2026-10-15",
    "compensation": "Unpaid independent collaboration; contributors are not charged and sales revenue is reinvested in the project (organizer’s stated terms).",
    "compensation_type": "unpaid",
    "region_scope": "worldwide",
    "rights_disclosure": "Creators retain copyright and ownership; selected contributors grant permission to publish, distribute, and promote the contribution and excerpts. Full terms follow selection.",
    "last_verified_at": "2026-09-30T19:38:52Z",
    "published": true,
    "description": "International call for original short horror combining prose, illustration, manga, comics, or experimental sequential art. Submit a proposal and samples rather than finished pages.",
    "roles": [
      "writer",
      "artist",
      "writer-artist",
      "team"
    ],
    "formats": [
      "pitch",
      "portfolio"
    ],
    "requirements": [
      {
        "id": "9f2b7379-4d4e-5215-b682-83972e1102dc",
        "opportunity_id": "8a94fc98-65bb-558e-af5e-8344e0e8dcf8",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "rights",
        "operator": "eq",
        "value": true,
        "wording": "Confirm that the proposal is original and that you hold the rights needed to submit and develop it.",
        "source_reference": "Who Can Apply / Originality",
        "source_url": "https://www.kkum.org/"
      },
      {
        "id": "37725f2d-ed95-5e19-b082-45d2c14b6d6e",
        "opportunity_id": "8a94fc98-65bb-558e-af5e-8344e0e8dcf8",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "synopsis",
        "operator": "eq",
        "value": true,
        "wording": "Prepare a 150–300 word story synopsis, estimated page count, and preferred format.",
        "source_reference": "What Should I Submit — Your Proposal",
        "source_url": "https://www.kkum.org/"
      },
      {
        "id": "42d27866-49e4-56a2-ba3e-61603f2b01ed",
        "opportunity_id": "8a94fc98-65bb-558e-af5e-8344e0e8dcf8",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "portfolio",
        "operator": "eq",
        "value": true,
        "wording": "Provide three relevant work examples or a portfolio link.",
        "source_reference": "What Should I Submit — Work Samples",
        "source_url": "https://www.kkum.org/"
      },
      {
        "id": "b8b150d5-3b36-5cfa-9d6b-bb95416f691b",
        "opportunity_id": "8a94fc98-65bb-558e-af5e-8344e0e8dcf8",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "genreFit",
        "operator": "eq",
        "value": true,
        "wording": "The proposal should be an original short horror work in one or more of the listed visual or written formats.",
        "source_reference": "What Should I Propose?",
        "source_url": "https://www.kkum.org/"
      },
      {
        "id": "dbf92e67-f981-58f6-acff-77949b918cf9",
        "opportunity_id": "8a94fc98-65bb-558e-af5e-8344e0e8dcf8",
        "kind": "preparation",
        "roles": [
          "team"
        ],
        "formats": [],
        "field": "teamRoles",
        "operator": "eq",
        "value": true,
        "wording": "Teams should identify each collaborator and their role in the proposal.",
        "source_reference": "About Your Work",
        "source_url": "https://www.kkum.org/"
      },
      {
        "id": "1ed25c58-5053-5e9e-ba60-edbcf4355f54",
        "opportunity_id": "8a94fc98-65bb-558e-af5e-8344e0e8dcf8",
        "kind": "review",
        "roles": [],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "The recommended finished length is about 4–12 pages; explain in the application if the idea needs a different length.",
        "source_reference": "Recommended Length",
        "source_url": "https://www.kkum.org/"
      },
      {
        "id": "927c7fc5-0ae0-51b5-910a-2d8d84255bf2",
        "opportunity_id": "8a94fc98-65bb-558e-af5e-8344e0e8dcf8",
        "kind": "review",
        "roles": [],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Do not create the complete finished work before selection.",
        "source_reference": "Important",
        "source_url": "https://www.kkum.org/"
      }
    ]
  },
  {
    "id": "2a2ebc1f-3fa9-53ee-bd8e-9abb2fcf99fe",
    "slug": "afrocomiccon-illustrated-revolution-adult",
    "title": "The Revolution Will Be Illustrated — adult call",
    "organizer": "OTEC / AfroComicCon",
    "category": "anthology",
    "official_url": "https://afrocomiccon.org/illustratedrevolution/",
    "status": "open",
    "deadline": null,
    "deadline_timezone": null,
    "deadline_note": "1 December 2026; submission time and timezone not stated.",
    "deadline_date": "2026-12-01",
    "compensation": "$125–$150 honorarium per accepted page, contingent on successful Spring 2027 Kickstarter funding (organizer’s stated terms).",
    "compensation_type": "conditional",
    "region_scope": "worldwide",
    "rights_disclosure": "The organizer states that original owners retain all rights to submitted comics.",
    "last_verified_at": "2026-09-30T19:38:52Z",
    "published": true,
    "description": "Worldwide adult-artist call for completed illustrations, cartoon strips, and graphic short stories about revolution and transformation. Priority is given to Black and Indigenous artists.",
    "roles": [
      "artist",
      "writer-artist",
      "team"
    ],
    "formats": [
      "completed short comic"
    ],
    "requirements": [
      {
        "id": "7987661f-4fb1-560d-838f-667bf9b93767",
        "opportunity_id": "2a2ebc1f-3fa9-53ee-bd8e-9abb2fcf99fe",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "rights",
        "operator": "eq",
        "value": true,
        "wording": "You must own the submitted comic or artwork.",
        "source_reference": "Adult Artist Guidelines — What We Are Looking For",
        "source_url": "https://afrocomiccon.org/illustratedrevolution/"
      },
      {
        "id": "9b7f254b-bc52-52e9-9fda-7d265dee1857",
        "opportunity_id": "2a2ebc1f-3fa9-53ee-bd8e-9abb2fcf99fe",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "storyPages",
        "operator": "lte",
        "value": 15,
        "wording": "Adult comic submissions may be no longer than 15 pages.",
        "source_reference": "Adult Artist Guidelines — What We Need",
        "source_url": "https://afrocomiccon.org/illustratedrevolution/"
      },
      {
        "id": "1b42092f-7878-59df-b24b-740f20f99e98",
        "opportunity_id": "2a2ebc1f-3fa9-53ee-bd8e-9abb2fcf99fe",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "bio",
        "operator": "eq",
        "value": true,
        "wording": "Prepare a creator biography of no more than 100 words.",
        "source_reference": "Adult Artist Submission Form",
        "source_url": "https://afrocomiccon.org/illustratedrevolution/"
      },
      {
        "id": "4a5e7e74-1783-56b0-bbe9-1ebfd25273e6",
        "opportunity_id": "2a2ebc1f-3fa9-53ee-bd8e-9abb2fcf99fe",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "fileFormat",
        "operator": "in",
        "value": [
          "pdf",
          "jpg"
        ],
        "wording": "Prepare the completed high-resolution artwork as a PDF or JPG at 300 DPI.",
        "source_reference": "Adult Artist Submission Form",
        "source_url": "https://afrocomiccon.org/illustratedrevolution/"
      },
      {
        "id": "81582aef-bc22-562c-ba5f-cdc44675c9d4",
        "opportunity_id": "2a2ebc1f-3fa9-53ee-bd8e-9abb2fcf99fe",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "dpi",
        "operator": "gte",
        "value": 300,
        "wording": "Export the completed artwork at 300 DPI or higher.",
        "source_reference": "Adult Artist Submission Form",
        "source_url": "https://afrocomiccon.org/illustratedrevolution/"
      },
      {
        "id": "b01f56c9-0989-5089-ab04-932f5b16c94b",
        "opportunity_id": "2a2ebc1f-3fa9-53ee-bd8e-9abb2fcf99fe",
        "kind": "review",
        "roles": [],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Confirm the required page dimensions with the organizer: the guidelines and upload form publish different sizes.",
        "source_reference": "Adult Artist Guidelines / Submission Form",
        "source_url": "https://afrocomiccon.org/illustratedrevolution/"
      },
      {
        "id": "78dd3e69-5f05-52f6-ac50-4fbe82212db1",
        "opportunity_id": "2a2ebc1f-3fa9-53ee-bd8e-9abb2fcf99fe",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "audienceFit",
        "operator": "eq",
        "value": true,
        "wording": "The work must uplift marginalized voices and avoid hate speech.",
        "source_reference": "Adult Artist Guidelines — What We Are Looking For",
        "source_url": "https://afrocomiccon.org/illustratedrevolution/"
      },
      {
        "id": "137bbb5f-e604-5baf-894c-25fdd349dcf5",
        "opportunity_id": "2a2ebc1f-3fa9-53ee-bd8e-9abb2fcf99fe",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "aiUsed",
        "operator": "eq",
        "value": false,
        "wording": "AI-generated content is not accepted.",
        "source_reference": "Adult Artist Guidelines — What We Are Looking For",
        "source_url": "https://afrocomiccon.org/illustratedrevolution/"
      }
    ]
  },
  {
    "id": "763354ef-5511-5cd5-814a-fbdc64c24cc2",
    "slug": "lumicpress-magazine",
    "title": "LumicPress Magazine one-shots",
    "organizer": "LumicPress",
    "category": "short-comic",
    "official_url": "https://lumicpress.com/lumicpress-magazine-submissions/",
    "status": "rolling",
    "deadline": null,
    "deadline_timezone": null,
    "deadline_date": null,
    "compensation": "$30 USD per published comic page, for 1–5 pages; payment is on publication rather than acceptance (organizer’s stated terms).",
    "compensation_type": "paid",
    "region_scope": "not-stated",
    "rights_disclosure": "Creators retain copyright and ownership and grant a non-exclusive, royalty-free license for one publication; reuse requires permission and additional payment.",
    "last_verified_at": "2026-09-30T19:38:52Z",
    "published": true,
    "description": "Rolling call for standalone black-and-white, manga-influenced comics for readers ages 6–14. Previously published work is allowed if it is not under an exclusive publishing agreement.",
    "roles": [
      "artist",
      "writer-artist",
      "team"
    ],
    "formats": [
      "completed short comic"
    ],
    "requirements": [
      {
        "id": "21a46c5c-fe45-53af-ac38-f2fc6404df26",
        "opportunity_id": "763354ef-5511-5cd5-814a-fbdc64c24cc2",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "rights",
        "operator": "eq",
        "value": true,
        "wording": "Submit only original work that you control; fan art is not accepted.",
        "source_reference": "Submission Guidelines",
        "source_url": "https://lumicpress.com/lumicpress-magazine-submissions/"
      },
      {
        "id": "82cfb399-2867-5d4e-897c-f34ac499b4cb",
        "opportunity_id": "763354ef-5511-5cd5-814a-fbdc64c24cc2",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "storyPages",
        "operator": "gte",
        "value": 1,
        "wording": "Comic submissions must contain at least one page.",
        "source_reference": "Submissions",
        "source_url": "https://lumicpress.com/lumicpress-magazine-submissions/"
      },
      {
        "id": "c467958f-54ea-581a-9181-10de9bfbf8ae",
        "opportunity_id": "763354ef-5511-5cd5-814a-fbdc64c24cc2",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "storyPages",
        "operator": "lte",
        "value": 5,
        "wording": "Comic submissions may contain no more than five pages.",
        "source_reference": "Submissions",
        "source_url": "https://lumicpress.com/lumicpress-magazine-submissions/"
      },
      {
        "id": "2ed96b06-98ae-5372-aa15-efa6855d187d",
        "opportunity_id": "763354ef-5511-5cd5-814a-fbdc64c24cc2",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "age",
        "operator": "gte",
        "value": 18,
        "wording": "Submitting creators must be 18 or older.",
        "source_reference": "Submission Guidelines",
        "source_url": "https://lumicpress.com/lumicpress-magazine-submissions/"
      },
      {
        "id": "4909e852-4e05-52b7-94ea-3243d41abf0d",
        "opportunity_id": "763354ef-5511-5cd5-814a-fbdc64c24cc2",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "aiUsed",
        "operator": "eq",
        "value": false,
        "wording": "AI-assisted work is not accepted.",
        "source_reference": "Submission Guidelines",
        "source_url": "https://lumicpress.com/lumicpress-magazine-submissions/"
      },
      {
        "id": "a0f5f0b1-77a7-5c25-ac86-e9d5db41c43d",
        "opportunity_id": "763354ef-5511-5cd5-814a-fbdc64c24cc2",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "audienceFit",
        "operator": "eq",
        "value": true,
        "wording": "Content must be suitable for children ages 6–14.",
        "source_reference": "Submission Guidelines",
        "source_url": "https://lumicpress.com/lumicpress-magazine-submissions/"
      },
      {
        "id": "7c7c4e2c-da3e-51b7-b66b-ea876a4922b5",
        "opportunity_id": "763354ef-5511-5cd5-814a-fbdc64c24cc2",
        "kind": "review",
        "roles": [],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Confirm that the comic is formatted for left-to-right reading.",
        "source_reference": "Submission Guidelines",
        "source_url": "https://lumicpress.com/lumicpress-magazine-submissions/"
      },
      {
        "id": "7c6225a7-93ca-5174-aa81-24218f7939f8",
        "opportunity_id": "763354ef-5511-5cd5-814a-fbdc64c24cc2",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "dpi",
        "operator": "gte",
        "value": 300,
        "wording": "Prepare the final pages at 300 DPI or higher.",
        "source_reference": "Submission Guidelines",
        "source_url": "https://lumicpress.com/lumicpress-magazine-submissions/"
      },
      {
        "id": "c704efd2-a501-5c24-85fd-a8213fda81d0",
        "opportunity_id": "763354ef-5511-5cd5-814a-fbdc64c24cc2",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "colorMode",
        "operator": "in",
        "value": [
          "black-and-white"
        ],
        "wording": "Prepare the final pages in black and white.",
        "source_reference": "Submission Guidelines",
        "source_url": "https://lumicpress.com/lumicpress-magazine-submissions/"
      },
      {
        "id": "2ac514da-c4ab-584e-adce-d05fe1d2795b",
        "opportunity_id": "763354ef-5511-5cd5-814a-fbdc64c24cc2",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "dimensionsReady",
        "operator": "eq",
        "value": true,
        "wording": "Prepare the final pages at 8.5 × 11 inches.",
        "source_reference": "Submission Guidelines",
        "source_url": "https://lumicpress.com/lumicpress-magazine-submissions/"
      }
    ]
  },
  {
    "id": "83b5633c-3bcf-5817-b38b-77816309bdf2",
    "slug": "viz-one-shots",
    "title": "VIZ manga one-shots",
    "organizer": "VIZ Media",
    "category": "short-comic",
    "official_url": "https://www.viz.com/blog/posts/submission-guidelines",
    "status": "rolling",
    "deadline": null,
    "deadline_timezone": null,
    "deadline_date": null,
    "compensation": null,
    "compensation_type": "undisclosed",
    "region_scope": "not-stated",
    "rights_disclosure": null,
    "last_verified_at": "2026-09-30T19:38:52Z",
    "published": true,
    "description": "Rolling portal for manga one-shots. Completed pages are preferred, but VIZ states that work in progress and thumbnails with an inked character design may be submitted.",
    "roles": [
      "writer-artist",
      "team"
    ],
    "formats": [
      "completed short comic",
      "pitch"
    ],
    "requirements": [
      {
        "id": "bb597860-7769-5d02-959c-de6ff44ec504",
        "opportunity_id": "83b5633c-3bcf-5817-b38b-77816309bdf2",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "storyPages",
        "operator": "gte",
        "value": 20,
        "wording": "A manga one-shot must be at least 20 pages.",
        "source_reference": "For One-Shots",
        "source_url": "https://www.viz.com/blog/posts/submission-guidelines"
      },
      {
        "id": "a1e262ee-8689-5f1b-bd5a-fd026cc864d4",
        "opportunity_id": "83b5633c-3bcf-5817-b38b-77816309bdf2",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "storyPages",
        "operator": "lte",
        "value": 50,
        "wording": "A manga one-shot may be no longer than 50 pages.",
        "source_reference": "For One-Shots",
        "source_url": "https://www.viz.com/blog/posts/submission-guidelines"
      },
      {
        "id": "8992207f-8d9d-5d0d-96e7-115bbe4aa63c",
        "opportunity_id": "83b5633c-3bcf-5817-b38b-77816309bdf2",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "synopsis",
        "operator": "eq",
        "value": true,
        "wording": "Prepare a story synopsis covering the direction and atmosphere of the manga.",
        "source_reference": "For both",
        "source_url": "https://www.viz.com/blog/posts/submission-guidelines"
      },
      {
        "id": "160593e7-51b8-5db7-b60c-ee6884fce446",
        "opportunity_id": "83b5633c-3bcf-5817-b38b-77816309bdf2",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "bio",
        "operator": "eq",
        "value": true,
        "wording": "Include creator biographies and creative goals.",
        "source_reference": "For both",
        "source_url": "https://www.viz.com/blog/posts/submission-guidelines"
      },
      {
        "id": "cdc90201-b381-5780-a863-2c6b564bb9b8",
        "opportunity_id": "83b5633c-3bcf-5817-b38b-77816309bdf2",
        "kind": "review",
        "roles": [],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Include character descriptions, target audience, comparable titles, and character designs when an artist is attached.",
        "source_reference": "For One-Shots / For both",
        "source_url": "https://www.viz.com/blog/posts/submission-guidelines"
      }
    ]
  },
  {
    "id": "846fd777-a8e2-5ad2-a2cc-0f3d57a4e64c",
    "slug": "dirty-water-hot-off-the-press",
    "title": "Hot off the Press",
    "organizer": "Dirty Water Comics",
    "category": "short-comic",
    "official_url": "https://www.dirtywatercomics.com/submissions/hotoffthepress",
    "status": "rolling",
    "deadline": null,
    "deadline_timezone": null,
    "deadline_date": null,
    "compensation": "Selected creators receive an honorarium; the organizer does not publish the amount or payment timing.",
    "compensation_type": "paid",
    "region_scope": "not-stated",
    "rights_disclosure": null,
    "last_verified_at": "2026-10-01T16:35:18Z",
    "published": true,
    "description": "Rolling digital showcase for previously unpublished standalone comics or excerpts from completed work, especially nonfiction, autobiographical, political, historical, and formally eclectic comics.",
    "roles": [
      "artist",
      "writer-artist",
      "team"
    ],
    "formats": [
      "completed short comic"
    ],
    "requirements": [
      {
        "id": "31be9b00-3d23-5d31-bdc2-e5fd9bfc5f5c",
        "opportunity_id": "846fd777-a8e2-5ad2-a2cc-0f3d57a4e64c",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "previouslyPublished",
        "operator": "eq",
        "value": false,
        "wording": "Submit a comic or excerpt that has not been published previously.",
        "source_reference": "What Should I Submit?",
        "source_url": "https://www.dirtywatercomics.com/submissions/hotoffthepress"
      },
      {
        "id": "abe4dc68-2e08-545f-a825-66a6c95333ed",
        "opportunity_id": "846fd777-a8e2-5ad2-a2cc-0f3d57a4e64c",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "storyPages",
        "operator": "gte",
        "value": 1,
        "wording": "The submission must contain at least one comic page.",
        "source_reference": "What Should I Submit?",
        "source_url": "https://www.dirtywatercomics.com/submissions/hotoffthepress"
      },
      {
        "id": "1d19c5ca-29bb-583b-87cf-c9662b1144e3",
        "opportunity_id": "846fd777-a8e2-5ad2-a2cc-0f3d57a4e64c",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "storyPages",
        "operator": "lte",
        "value": 15,
        "wording": "The submission may contain no more than 15 pages.",
        "source_reference": "What Should I Submit?",
        "source_url": "https://www.dirtywatercomics.com/submissions/hotoffthepress"
      },
      {
        "id": "8d99ff6b-6ddb-5fa0-8086-eea5520fda29",
        "opportunity_id": "846fd777-a8e2-5ad2-a2cc-0f3d57a4e64c",
        "kind": "review",
        "roles": [],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Review the literary and nonfiction focus and the restrictions on conventional superhero, horror, science-fiction, and fantasy work.",
        "source_reference": "We are interested in / What Should I Submit?",
        "source_url": "https://www.dirtywatercomics.com/submissions/hotoffthepress"
      },
      {
        "id": "2c4ff42f-04fc-56e6-bc0b-5526fa251fa3",
        "opportunity_id": "846fd777-a8e2-5ad2-a2cc-0f3d57a4e64c",
        "kind": "review",
        "roles": [],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Email the completed submission with “Hot off the Press” in the subject line.",
        "source_reference": "Submission instructions",
        "source_url": "https://www.dirtywatercomics.com/submissions/hotoffthepress"
      }
    ]
  },
  {
    "id": "91dfa255-b820-5a0f-8068-bf438146e1a2",
    "slug": "grub-street-volume-76-comics",
    "title": "Grub Street Volume 76 — comics",
    "organizer": "Grub Street Literary Magazine",
    "category": "short-comic",
    "official_url": "https://grubstreet.submittable.com/submit",
    "status": "open",
    "deadline": null,
    "deadline_timezone": null,
    "deadline_date": "2026-12-15",
    "deadline_note": "15 December 2026; submission time and timezone not stated.",
    "compensation": null,
    "compensation_type": "undisclosed",
    "region_scope": "not-stated",
    "rights_disclosure": null,
    "last_verified_at": "2026-10-01T16:35:18Z",
    "published": true,
    "description": "Blind-reviewed literary magazine call accepting up to five previously unpublished comic pieces. Each piece must be under ten pages and supplied as high-resolution image files.",
    "roles": [
      "artist",
      "writer-artist",
      "team"
    ],
    "formats": [
      "completed short comic"
    ],
    "requirements": [
      {
        "id": "31173fe7-3f73-583d-8b66-43af4f1090d8",
        "opportunity_id": "91dfa255-b820-5a0f-8068-bf438146e1a2",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "previouslyPublished",
        "operator": "eq",
        "value": false,
        "wording": "Only previously unpublished work, in print or online, is considered.",
        "source_reference": "Submission Guidelines",
        "source_url": "https://grubstreet.submittable.com/submit"
      },
      {
        "id": "1ffaefba-16cf-5c9e-8745-76a54811f761",
        "opportunity_id": "91dfa255-b820-5a0f-8068-bf438146e1a2",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "storyPages",
        "operator": "lte",
        "value": 9,
        "wording": "Each comic piece must be under ten pages.",
        "source_reference": "Comics guidelines",
        "source_url": "https://grubstreet.submittable.com/submit"
      },
      {
        "id": "f6175a12-327d-5e63-bd4b-89ee20f09ca9",
        "opportunity_id": "91dfa255-b820-5a0f-8068-bf438146e1a2",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "fileFormat",
        "operator": "in",
        "value": [
          "png",
          "tif",
          "jpg"
        ],
        "wording": "Prepare each comic as a PNG, TIFF, or high-quality JPEG file.",
        "source_reference": "Comics guidelines",
        "source_url": "https://grubstreet.submittable.com/submit"
      },
      {
        "id": "b8903539-05c3-5123-9c50-9de1c7721bf4",
        "opportunity_id": "91dfa255-b820-5a0f-8068-bf438146e1a2",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "dpi",
        "operator": "gte",
        "value": 300,
        "wording": "Prepare comic files at 300 DPI or higher.",
        "source_reference": "Comics guidelines",
        "source_url": "https://grubstreet.submittable.com/submit"
      },
      {
        "id": "c49e19fa-b1ea-5f8b-81ef-537790769241",
        "opportunity_id": "91dfa255-b820-5a0f-8068-bf438146e1a2",
        "kind": "preparation",
        "roles": [],
        "formats": [],
        "field": "dimensionsReady",
        "operator": "eq",
        "value": true,
        "wording": "Each comic image must be at least 4 × 6 inches.",
        "source_reference": "Comics guidelines",
        "source_url": "https://grubstreet.submittable.com/submit"
      },
      {
        "id": "555139bd-8fc0-5e05-9b13-2892c8b85766",
        "opportunity_id": "91dfa255-b820-5a0f-8068-bf438146e1a2",
        "kind": "review",
        "roles": [],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Remove identifying information from the work and its file name before submitting.",
        "source_reference": "Blind-review process",
        "source_url": "https://grubstreet.submittable.com/submit"
      }
    ]
  },
  {
    "id": "2c191538-34f7-5564-a8f6-a21b2ccb9183",
    "slug": "anmly-graphic-narratives-2026-27",
    "title": "ANMLY graphic narratives",
    "organizer": "ANMLY",
    "category": "short-comic",
    "official_url": "https://anmly.org/calls/",
    "status": "open",
    "deadline": null,
    "deadline_timezone": null,
    "deadline_date": "2027-02-01",
    "deadline_note": "Current reading period closes 1 February 2027; submission time and timezone not stated.",
    "compensation": null,
    "compensation_type": "undisclosed",
    "region_scope": "not-stated",
    "rights_disclosure": null,
    "last_verified_at": "2026-10-01T16:35:18Z",
    "published": true,
    "description": "Current reading period for challenging, previously unpublished comics and graphic narratives. ANMLY publishes work online and accepts graphic narratives during its general submission windows.",
    "roles": [
      "artist",
      "writer-artist",
      "team"
    ],
    "formats": [
      "completed short comic"
    ],
    "requirements": [
      {
        "id": "dfefccd5-aecd-579a-8d8e-deed4615ce42",
        "opportunity_id": "2c191538-34f7-5564-a8f6-a21b2ccb9183",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "previouslyPublished",
        "operator": "eq",
        "value": false,
        "wording": "The work must be previously unpublished, including on a personal blog.",
        "source_reference": "General Calls for Submissions",
        "source_url": "https://anmly.org/calls/"
      },
      {
        "id": "ebab2f2d-b08c-5a5c-858d-418348675a0d",
        "opportunity_id": "2c191538-34f7-5564-a8f6-a21b2ccb9183",
        "kind": "eligibility",
        "roles": [],
        "formats": [],
        "field": "aiUsed",
        "operator": "eq",
        "value": false,
        "wording": "AI-generated or AI-assisted writing and art are not accepted.",
        "source_reference": "General Calls for Submissions",
        "source_url": "https://anmly.org/calls/"
      },
      {
        "id": "26b1ed6e-b8e9-5240-be8a-6e755491d9fd",
        "opportunity_id": "2c191538-34f7-5564-a8f6-a21b2ccb9183",
        "kind": "review",
        "roles": [],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "The standard submission fee is $3; the organizer provides a hardship waiver by email.",
        "source_reference": "General Calls for Submissions",
        "source_url": "https://anmly.org/calls/"
      },
      {
        "id": "e19ca546-335d-581a-b6ef-161ac36d8309",
        "opportunity_id": "2c191538-34f7-5564-a8f6-a21b2ccb9183",
        "kind": "review",
        "roles": [],
        "formats": [],
        "field": null,
        "operator": "review",
        "value": null,
        "wording": "Review previous ANMLY issues to confirm that the graphic narrative fits the journal’s experimental and boundary-pushing focus.",
        "source_reference": "General Calls for Submissions",
        "source_url": "https://anmly.org/calls/"
      }
    ]
  }
]$catalog$::jsonb;
  opportunity jsonb;
  requirement jsonb;
  stored_opportunity_id uuid;
begin
  for opportunity in select value from jsonb_array_elements(catalog)
  loop
    insert into public.opportunities (
      id, slug, title, organizer, category, official_url, status, deadline,
      deadline_timezone, deadline_note, deadline_date, compensation,
      compensation_type, region_scope, rights_disclosure, last_verified_at,
      published, description, roles, formats, updated_at
    ) values (
      (opportunity->>'id')::uuid,
      opportunity->>'slug',
      opportunity->>'title',
      opportunity->>'organizer',
      opportunity->>'category',
      opportunity->>'official_url',
      opportunity->>'status',
      nullif(opportunity->>'deadline', '')::timestamptz,
      nullif(opportunity->>'deadline_timezone', ''),
      nullif(opportunity->>'deadline_note', ''),
      nullif(opportunity->>'deadline_date', '')::date,
      nullif(opportunity->>'compensation', ''),
      opportunity->>'compensation_type',
      opportunity->>'region_scope',
      nullif(opportunity->>'rights_disclosure', ''),
      (opportunity->>'last_verified_at')::timestamptz,
      true,
      opportunity->>'description',
      array(select jsonb_array_elements_text(opportunity->'roles')),
      array(select jsonb_array_elements_text(opportunity->'formats')),
      (opportunity->>'last_verified_at')::timestamptz
    )
    on conflict (slug) do update set
      title = excluded.title,
      organizer = excluded.organizer,
      category = excluded.category,
      official_url = excluded.official_url,
      status = excluded.status,
      deadline = excluded.deadline,
      deadline_timezone = excluded.deadline_timezone,
      deadline_note = excluded.deadline_note,
      deadline_date = excluded.deadline_date,
      compensation = excluded.compensation,
      compensation_type = excluded.compensation_type,
      region_scope = excluded.region_scope,
      rights_disclosure = excluded.rights_disclosure,
      last_verified_at = excluded.last_verified_at,
      published = true,
      description = excluded.description,
      roles = excluded.roles,
      formats = excluded.formats,
      updated_at = excluded.updated_at
    returning id into stored_opportunity_id;

    delete from public.requirements where requirements.opportunity_id = stored_opportunity_id;
    for requirement in select value from jsonb_array_elements(opportunity->'requirements')
    loop
      insert into public.requirements (
        id, opportunity_id, kind, roles, formats, field, operator, value,
        wording, source_reference, source_url
      ) values (
        (requirement->>'id')::uuid,
        stored_opportunity_id,
        requirement->>'kind',
        array(select jsonb_array_elements_text(requirement->'roles')),
        array(select jsonb_array_elements_text(requirement->'formats')),
        nullif(requirement->>'field', ''),
        requirement->>'operator',
        nullif(requirement->'value', 'null'::jsonb),
        requirement->>'wording',
        requirement->>'source_reference',
        requirement->>'source_url'
      );
    end loop;

    if not exists (
      select 1 from public.verification_events
      where verification_events.opportunity_id = stored_opportunity_id
        and result = 'verified'
        and checked_at = (opportunity->>'last_verified_at')::timestamptz
    ) then
      insert into public.verification_events (
        opportunity_id, checked_at, result, admin_note, checked_by
      ) values (
        stored_opportunity_id,
        (opportunity->>'last_verified_at')::timestamptz,
        'verified',
        'Imported from the reviewed ComicReady catalog. Official source and structured requirements were manually checked.',
        null
      );
    end if;
  end loop;
end
$migration$;
